### ISSUE TITLE
Install-ChocolateyPackage command not recognized

### ISSUE THREAD

**Issue by pieter-venter** [mwrock/boxstarter#104]
Steps to reproduce:

1. Create a gist. It only contains this line:
> choco install visualstudio2015community -y

2. On a Windows 2012 R2 server, use the clickonce launcher and browse to
http://boxstarter.org/package/url?https://gist.github.com/user/id/raw/

3. It downloads and starts the script. It fails with this error:

> Install-ChocolateyPackage VisualStudio2015Community exe /Passive /NoRestart /Lo
g C:\Users\xxx~1\AppData\Local\Temp\vs.log http://download.microsoft.com/dow
nload/0/B/C/0BC321A4-013F-479C-84E6-4A2F90B11269/vs_community.exe -validExitCod
es 0 3010 2147781575 -2147185721
Write-Error : Package 'VisualStudio2015Community v14.0.23107.0' did not install
 successfully: The term 'Install-ChocolateyPackage' is not recognized as the na
me of a cmdlet, function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is correct and try
 again.
At C:\Users\xxx\AppData\Local\Apps\2.0\LEXY8CA9.B1Y\MWN47328.Y66\boxs.
.tion_4b037e62ccd024b7_0002.0005_3e2e44b7c485849f\Chocolatey\chocolateyinstall\
functions\Chocolatey-NuGet.ps1:90 char:17

Not sure how to troubleshoot. It's almost as if the Chocolately commands are not loaded or something. Is it an issue with the Visual Studio package or what am I missing?

**Comment by mwrock** [comment]
Thanks a ton for reporting this. Looks like when a package creates its own internal module and then calls choco functions from that, boxstarter was breaking. The fix was just released in 2.5.21.

**Comment by pieter-venter** [comment]
Thanks for jumping on it so fast. I can confirm that it is working properly now.
