### ISSUE TITLE
Boxstarter blocks on choco warning "Unable to generate `'$ignoreFile`'"

### ISSUE THREAD

**Issue by riezebosch** [mwrock/boxstarter#110]
When installing Visual Studio in a virtual from the ISO choco writes the warning it fails to generate the vs_enteprise.exe.ignore' file and boxstarter displays this message on the remote in a blocking dialog that asks for confirmation.

Chocolatey write this warning when using Install-ChocolateyInstallPackage and it is unable to create an ignore file due to the medium or the lack of write access: https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1#L69

Is it possible to ignore this warning and just continue install? Because in the end the package is installed successfully.

Here is my install script: https://gist.github.com/riezebosch/d764ce9414599a75ecd8

It looks related to this issue: https://github.com/chocolatey/chocolatey/issues/380. It also fails the installation of the package so it keeps trying to install the package after a reboot. This is no longer the case when installing locally (with or without boxstarter).

**Comment by mwrock** [comment]
Hmm. I have not seen this before. Its probably not boxstarter directly doing this but if you could provide a screen shot of the dialog it would help to nail down why this is happening.

**Comment by riezebosch** [comment]
For me this is no longer very relevant. I abandoned the installation from ISO.
