### ISSUE TITLE
Docs don't explain how to execute local script using web launch

### ISSUE THREAD

**Issue by jptillman** [mwrock/boxstarter#116]
Step 2 of the "Launch from the web" doc page states that you can save your script as a nuget package, on a network location, as a local script, or at a URL.  Then it goes on to show you only how to load from a gist and never mentions the others again.  I need to execute a local script, and I don't want to put it in a gist just to execute it.  I've tried a local file:/// url, but that is ignored by the web launcher.

What is the proper syntax to launch a local file when using the web launcher?

**Comment by jptillman** [comment]
Ok, I found my own answer, which is to use this:

START http://boxstarter.org/package/url?z:/MyScript.ps1

where z: is the drive, of course.

**Comment by jptillman** [comment]
Figured it out.  I have to use a standard filesystem path, rather than file:///

START http://boxstarter.org/package/url?e:\myscript.ps1

**Comment by mwrock** [comment]
Reopening because I think the docs could explain this better.

**Comment by lholman** [comment]
@mwrock I'm assuming we're talking about the docs here https://github.com/mwrock/boxstarter/blob/master/Web/WebLauncher.cshtml#L43
Happy to submit a PR with some more detail around this but aware you're pretty tied up on the choco branch, how would you like this submitted?

**Comment by mwrock** [comment]
@lholman if you wanted to add some clarity that would be awesome. L43 refers to actual packages where the comment here is in regards to single scripts. the next line https://github.com/mwrock/boxstarter/blob/master/Web/WebLauncher.cshtml#L44. The page only provides how you would do this with an http url, but you could also pass a local file. This probably just neds a brief note at the end of Step 2 stating that you can also use a local file with a one line example.
