### ISSUE TITLE
Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: -y

### ISSUE THREAD

**Issue by filippobottega** [mwrock/boxstarter#123]
Hello,
  I have an issue installing boxstarter from scratch. How can I solve this issue?

  Thank you for your support.

  See chocolateyInstall.log below:

20151109-10:41:53 [DEBUG] Test-ProcessAdminRights: returning True
20151109-10:41:54 [DEBUG] Administrator installing so using Machine environment variable target instead of User.
20151109-10:41:54 [CHOCO] Creating ChocolateyInstall as an Environment variable (targeting 'Machine') and setting it to 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey'
20151109-10:41:54 [DEBUG] Running 'Install-ChocolateyEnvironmentVariable' with variableName:'ChocolateyInstall' and variableValue:'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey'
20151109-10:41:54 [DEBUG] Test-ProcessAdminRights: returning True
20151109-10:42:19 [CHOCO] We are setting up the Chocolatey repository for NuGet packages that should be at the machine level. Think executables/application packages, not library packages.
That is what Chocolatey NuGet goodness is for. The repository is set up at 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey'.
The packages themselves go to 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey\lib' (i.e. C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey\bin' and points to an executable in 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey\lib\yourPackageName'.

Creating Chocolatey NuGet folders if they do not already exist.

20151109-10:42:19 [CHOCO] Copying the contents of 'C:\Users\Filippo\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall' to 'C:\Users\Filippo\AppData\Roaming\Boxstarter\Chocolatey'.
20151109-10:42:47 [CHOCO] Chocolatey is now ready.
You can call chocolatey from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles first prior to using chocolatey.
20151109-10:43:37 [CHOCO] The Boxstarter.Chocolatey Module has been copied to C:\Users\Filippo\AppData\Roaming\Boxstarter and added to your Module path. 
You will need to open a new console for the path to be visible.
Use 'Get-Module Boxstarter.* -ListAvailable' to list all Boxstarter Modules.
To list all available Boxstarter Commands, use:
PS:>Import-Module Boxstarter.Chocolatey
PS:>Get-Command -Module Boxstarter.*

To find more info visit http://Boxstarter.org or use:
PS:>Import-Module Boxstarter.Chocolatey
PS:>Get-Help Boxstarter
20151109-10:43:37 [DEBUG] Running 'Get-ChocolateyBins' for C:\ProgramData\chocolatey\lib\boxstarter.chocolatey.2.5.21
20151109-10:43:38 [DEBUG]   __ Executable Links (*.exe) __
20151109-10:43:38 [DEBUG] Looking for executables in folder: C:\ProgramData\chocolatey\lib\boxstarter.chocolatey.2.5.21
Adding batch files for any executables found to a location on PATH. In other words the executable will be available from ANY command line/powershell prompt.
20151109-10:43:38 [DEBUG] There are no executables (that are not ignored) in the package.
20151109-10:43:38 [DEBUG] Evaluating NuGet output for line: Installing 'Boxstarter.HyperV 2.5.21'.

20151109-10:43:38 [DEBUG] Evaluating NuGet output for line: Successfully installed 'Boxstarter.HyperV 2.5.21'.

20151109-10:43:38 [DEBUG] NuGet installed Boxstarter.HyperV. If we are ignoring dependencies (False) then we will clean this up.
20151109-10:43:39 [CHOCO]  
20151109-10:43:39 [CHOCO] Boxstarter.HyperV v2.5.21
20151109-10:43:39 [DEBUG] Running 'Delete-ExistingErrorLog' for Boxstarter.HyperV
20151109-10:43:39 [DEBUG] Looking for failure log at 'C:\Users\Filippo\AppData\Local\Temp\chocolatey\Boxstarter.HyperV\failure.log'
20151109-10:43:39 [DEBUG] Running 'Run-ChocolateyPS1' for Boxstarter.HyperV with packageFolder:'C:\ProgramData\chocolatey\lib\Boxstarter.HyperV.2.5.21', action: 'install'
20151109-10:43:40 [DEBUG]   __ PowerShell install (chocolateyinstall.ps1) __
20151109-10:43:40 [DEBUG]   Looking for chocolateyinstall.ps1 in folder 'C:\ProgramData\chocolatey\lib\Boxstarter.HyperV.2.5.21'. If chocolateyinstall.ps1 is found, it will be run.
20151109-10:43:40 [DEBUG] Action file is 'chocolateyinstall.ps1'
20151109-10:43:40 [DEBUG] Running 'C:\ProgramData\chocolatey\lib\Boxstarter.HyperV.2.5.21\tools\chocolateyinstall.ps1'
20151109-10:44:31 [CHOCO] The Boxstarter.HyperV Module has been copied to C:\Users\Filippo\AppData\Roaming\Boxstarter and added to your Module path. 
You will need to open a new console for the path to be visible.
Use 'Get-Module Boxstarter.* -ListAvailable' to list all Boxstarter Modules.
To list all available Boxstarter Commands, use:
PS:>Import-Module Boxstarter.HyperV
PS:>Get-Command -Module Boxstarter.*

To find more info visit http://Boxstarter.org or use:
PS:>Import-Module Boxstarter.HyperV
PS:>Get-Help Boxstarter
20151109-10:44:31 [DEBUG] Running 'Get-ChocolateyBins' for C:\ProgramData\chocolatey\lib\Boxstarter.HyperV.2.5.21
20151109-10:44:31 [DEBUG]   __ Executable Links (*.exe) __
20151109-10:44:31 [DEBUG] Looking for executables in folder: C:\ProgramData\chocolatey\lib\Boxstarter.HyperV.2.5.21
Adding batch files for any executables found to a location on PATH. In other words the executable will be available from ANY command line/powershell prompt.
20151109-10:44:31 [DEBUG] There are no executables (that are not ignored) in the package.
20151109-10:44:32 [DEBUG] Evaluating NuGet output for line: Installing 'boxstarter 2.5.21'.

20151109-10:44:32 [DEBUG] Evaluating NuGet output for line: Successfully installed 'boxstarter 2.5.21'.

20151109-10:44:32 [DEBUG] NuGet installed boxstarter. If we are ignoring dependencies (False) then we will clean this up.
20151109-10:44:32 [CHOCO]  
20151109-10:44:32 [CHOCO] boxstarter v2.5.21
20151109-10:44:33 [DEBUG] Running 'Delete-ExistingErrorLog' for boxstarter
20151109-10:44:33 [DEBUG] Looking for failure log at 'C:\Users\Filippo\AppData\Local\Temp\chocolatey\boxstarter\failure.log'
20151109-10:44:33 [DEBUG] Running 'Run-ChocolateyPS1' for boxstarter with packageFolder:'C:\ProgramData\chocolatey\lib\boxstarter.2.5.21', action: 'install'
20151109-10:44:33 [DEBUG]   __ PowerShell install (chocolateyinstall.ps1) __
20151109-10:44:33 [DEBUG]   Looking for chocolateyinstall.ps1 in folder 'C:\ProgramData\chocolatey\lib\boxstarter.2.5.21'. If chocolateyinstall.ps1 is found, it will be run.
20151109-10:44:33 [DEBUG] Action file is 'chocolateyinstall.ps1'
20151109-10:44:33 [DEBUG] Running 'C:\ProgramData\chocolatey\lib\boxstarter.2.5.21\tools\chocolateyinstall.ps1'
20151109-10:44:34 [CHOCO] To load all Boxstarter Modules immediately, just enter 'BoxstarterShell'.
20151109-10:44:34 [CHOCO] Interested in Windows Azure VM integration? Run CINST Boxstarter.Azure to install Boxstarter's Azure integration.
20151109-10:44:34 [DEBUG] Running 'Get-ChocolateyBins' for C:\ProgramData\chocolatey\lib\boxstarter.2.5.21
20151109-10:44:34 [DEBUG]   __ Executable Links (*.exe) __
20151109-10:44:34 [DEBUG] Looking for executables in folder: C:\ProgramData\chocolatey\lib\boxstarter.2.5.21
Adding batch files for any executables found to a location on PATH. In other words the executable will be available from ANY command line/powershell prompt.
20151109-10:44:35 [DEBUG] There are no executables (that are not ignored) in the package.
20151109-10:44:35 [DEBUG] Evaluating NuGet output for line: 
20151109-10:44:35 [CHOCO] Finished installing 'Boxstarter' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
20151109-10:44:35 [DEBUG] Running 'Chocolatey-Install' for '-y' with source: '', version: '2.5.21', installerArguments:''
20151109-10:44:35 [DEBUG] Running 'Chocolatey-NuGet' for -y with source:''. Force? False
20151109-10:44:36 [CHOCO] Chocolatey (v0.9.8.28) is installing '-y' and dependencies. By installing you accept the license for '-y' and each dependency you are installing.
20151109-10:44:36 [DEBUG] Installing packages to "C:\ProgramData\chocolatey\lib".
20151109-10:44:36 [DEBUG] Running 'Run-NuGet' for -y with source: '', version:'2.5.21'
20151109-10:44:36 [DEBUG] ___ NuGet ____
20151109-10:44:36 [DEBUG] Running 'Get-ConfigValue' with configValue:'useNuGetForSources'
20151109-10:44:36 [DEBUG] Running 'Get-UserConfigValue' with configValue:'useNuGetForSources'
20151109-10:44:36 [DEBUG] After checking the user config the value of 'useNuGetForSources' is ''
20151109-10:44:37 [DEBUG] Value not found in the user config file - checking the global config
20151109-10:44:37 [DEBUG] Running 'Get-GlobalConfigValue' with configValue:'useNuGetForSources'
20151109-10:44:37 [DEBUG] After checking the global config the value of 'useNuGetForSources' is 'false'
20151109-10:44:37 [DEBUG] Running 'Get-UserConfigValue' with configValue:'sources'
20151109-10:44:37 [DEBUG] Running 'Get-GlobalConfigValue' with configValue:'sources'
20151109-10:44:37 [DEBUG] Using global sources
20151109-10:44:38 [DEBUG] Using '-Source "https://chocolatey.org/api/v2/;"' as the source arguments
20151109-10:44:38 [DEBUG] Calling 'C:\ProgramData\chocolatey\chocolateyinstall\nuget.exe' install -y -OutputDirectory "C:\ProgramData\chocolatey\lib" -Source "https://chocolatey.org/api/v2/;" -NonInteractive -NoCache -Version 2.5.21
20151109-10:44:39 [DEBUG] 
20151109-10:44:39 [CHOCO] Opzione sconosciuta: '-y'

20151109-10:44:39 [CHOCO] Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: -y
20151109-10:44:39 [DEBUG] Running 'Get-ConfigValue' with configValue:'ksMessage'
20151109-10:44:39 [DEBUG] Running 'Get-UserConfigValue' with configValue:'ksMessage'
20151109-10:44:39 [DEBUG] After checking the user config the value of 'ksMessage' is ''
20151109-10:44:40 [DEBUG] Value not found in the user config file - checking the global config
20151109-10:44:40 [DEBUG] Running 'Get-GlobalConfigValue' with configValue:'ksMessage'
20151109-10:44:40 [DEBUG] After checking the global config the value of 'ksMessage' is 'true'
20151109-10:44:40 [CHOCO] 
Did you know we are rewriting Chocolatey? The new
version is much more stable and secure.

Find out more and support the future of Chocolatey
at https://bit.ly/chocolateykickstarter

Disable this message by changing ksMessage to false in chocolatey.config.
20151109-10:44:40 [DEBUG] Exiting with non-zero exit code.

**Comment by mwrock** [comment]
It looks as though your machine has a very old version of chocolatey installed (0.9.8.28) which is even older than the version of chocolatey that boxstarter installs as its private version. You might try updating to the latest chocolatey and then try installing boxstarter again.

**Comment by filippobottega** [comment]
Thank you for your answer,
  I have uninstalled all previous versions of chocolatey and then I have installed chocolatey 0.9.9.11 with OneGet and boxstarter using OneGet and chocolatey without errors. I'll try to use boxstarter and if I'll find some errors I'll update this issue.

  Best regards,
    Filippo.

**Comment by mwrock** [comment]
closing for now but please reopen if you see this again.
