### ISSUE TITLE
Enables Windows Update uncondtionally

### ISSUE THREAD

**Issue by riezebosch** [mwrock/boxstarter#127]
For my training environment I want to have the Windows Update disabled completely. But after provisioning the lab environment using BoxStarter the Windows Update is always enabled again no matter what the original configuration was. 

From the source I see this happening inside the finally clause in the Invoke-BoxStarter function [invokes](https://github.com/mwrock/boxstarter/blob/5d388c4109f34c656f497ba831913f6b7e0435fb/Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1#L115) the Cleanup-Boxstarter which [invokes](https://github.com/mwrock/boxstarter/blob/5d388c4109f34c656f497ba831913f6b7e0435fb/Boxstarter.Bootstrapper/Cleanup-Boxstarter.ps1#L8) the [Start-UpdateServices](https://github.com/mwrock/boxstarter/blob/5d388c4109f34c656f497ba831913f6b7e0435fb/Boxstarter.Bootstrapper/Start-UpdateServices.ps1) function which does not consider the original state of specified regkey.

**Comment by mwrock** [comment]
Yep. We should definitely restore it to its original state

**Comment by riezebosch** [comment]
Created a pull request: https://github.com/mwrock/boxstarter/pull/134

**Comment by mwrock** [comment]
fixed by #134 released in 2.6.16
