### ISSUE TITLE
File helpers\functions\Format-FileSize.ps1 no longer exists in Chocolatey

### ISSUE THREAD

**Issue by brennanfee** [mwrock/boxstarter#128]
Line 62 in New-PackageFromScript.ps1 needs to be removed.  Seems to work fine without it but perhaps formatting is off.  Still, poor formatting would be superior to a hard error on attempting to source the file.

**Comment by mwrock** [comment]
Its actually a new file in the current beta version which is embedded in boxstarter. Looks like running boxstarter on a system with the current version of chocolatey installed (obviously a common case) this file is not added.

I'll have this fixed today. Thanks for reporting!
