### ISSUE TITLE
Error under Boxstarter 2.6.2 displayed when old Chocolatey is installed

### ISSUE THREAD

**Issue by it-praktyk** [mwrock/boxstarter#133]
I've installed today Boxstarter v. 2.6.2 on the host were I've installed Chocolatey v. 0.9.8.27.

At the end of installation error was displayed like on the screenshot.

![boxstarter_installation_error](https://cloud.githubusercontent.com/assets/4910261/11796852/0f4aae68-a2bf-11e5-84cf-4d15fad1e1df.jpg)

Proposed solution: check the Chocolatey version under installation, compare with a prefered version and invoke "choco update" if needed

**Comment by mwrock** [comment]
Oh interesting. Looks like those errors are occuring during the call to:
```
cinst boxstarter
```
is that right?

**Comment by it-praktyk** [comment]
I'll try reproduce this situation tomorrow (?).

**Comment by mwrock** [comment]
no need. i see the issue thanks!
