### ISSUE TITLE
Error while invoking script from web

### ISSUE THREAD

**Issue by MNie** [mwrock/boxstarter#135]
Hi, 

I have a problem with running a script from a boxstarter web runner. I get following error:
![aa](https://cloud.githubusercontent.com/assets/7689103/11810029/5c362cea-a32b-11e5-9178-33d265c1e162.png)

Problem arises regardless of what the script do. I think, the problem that possibly cause this, is in this invocation:
Problem occurs whenever the script looks like if its only set something, or install a single application.
I think, it could be a problem here:
![image](https://cloud.githubusercontent.com/assets/7689103/11810251/02f5641e-a32d-11e5-895f-000afe502905.png)

But it's only a guess..

**Comment by mwrock** [comment]
Hmm. Yeah the actual error is in the invocation and is here: https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Chocolatey/invoke-chocolatey.ps1#L246

So `(Get-Location).Path` must be returning something malformed. I'm investigating but can you tell me if there is anything special about your system? I believe that would return a path under your user's appdata. Any special characters in your user name?

**Comment by MNie** [comment]
Hi @mwrock 

No, there is not any special characters in my username. Anything special about my system? It's a windows server 2012, so i suppose nothing special :).

**Comment by mwrock** [comment]
2012 or 2012R2?

Would you mind `cd`ing in a powershell console to the directory mentioned in the error just above boxstarter? The one ending in 70df. Then running:
```
[System.IO.Directory]::SetCurrentDirectory((Get-Location).Path)
```
I'd be curious if that reproduces the error. If not, try `cd`ing to the BuildPackages directory just below that one and running the same command.

I really appreciate it!

**Comment by MNie** [comment]
2012R2.

![image](https://cloud.githubusercontent.com/assets/7689103/11811687/4e70ec42-a337-11e5-9d5e-7a87ee7d2782.png)

**Comment by mwrock** [comment]
hmm. ok. Sometime today I'm going to release a new version that will contain some debug logging around that code. I'll let you know when that happens and then it would be great if you could rerun boxstarter and then send me some details from the log. I'll let you know where to find them. Thanks!

**Comment by mwrock** [comment]
Just released 2.6.16. If you have a chance to run your package on that, look in the log file afterwards located in `$env:LocalAppData\Boxstarter\Boxstarter.log`. Towards the end you should find entries similar to:
```
[2015-12-15T06:17:06.0382648-08:00:::PID 1780] [WIN-PQGGDBC3BHO]Boxstarter: setting current directory location to C:\Users\Administrator\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey
```
and
```
[2015-12-15T06:17:31.3002022-08:00:::PID 1780] [WIN-PQGGDBC3BHO]Boxstarter: restoring current directory location to C:\Users\Administrator\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey
```

If you could find the very last entry, which should be the one just before the exception I imagine, I suspect there will be something there to clue us in on the problem.

Thanks!

**Comment by MNie** [comment]
![image](https://cloud.githubusercontent.com/assets/7689103/11835386/6c24a89a-a3d3-11e5-825e-8127709ede2a.png)

Also I know that size of an string in path, in windows doesn't matter, but I have a C:\Windows\System32 path instead of C:\Windows\system32.

**Comment by mwrock** [comment]
ok that log snippet is very helpful. Can you tell me how you are calling boxstarter? I'm assuming you are using `start http://boxstarter.com/package/url?...`. I think this is related to the format of the url you are including.

**Comment by MNie** [comment]
Yup, You are right. I invoke it as follows:
"START http://boxstarter.org/package/url?urlToMyScript"

**Comment by mwrock** [comment]
what format is the url to your script? I'm guessing it is not http. Is it file:// ?

**Comment by MNie** [comment]
It is http://machine.bla.bla.pl/folder1/folder2/scriptToRun.txt

**Comment by mwrock** [comment]
Sorry for all the questions but I cant seem to be able to reproduce this. The problem is the `Microsoft.PowerShell.Core\FileSystem::\\` before the path. I have seen this before when grabing the path of a UNC. Can you tell me if the path to the package after "\\" is a normal drive letter style path or a UNC file share path.

**Comment by mwrock** [comment]
Well regardless of how this is originating, I do believe I found a fix and will be releasing later today.

**Comment by mwrock** [comment]
I'll comment when this is released.

**Comment by mwrock** [comment]
released 2.6.20 with the fix. Let me know if that fixes you or not.

**Comment by MNie** [comment]
Yes, I see that. I run the script and it looks, that it works fine.
But, I see that there is some warnings/erros (warnings, because scripts doesn't stop if they occurs).
Here is a screen from logs:
![image](https://cloud.githubusercontent.com/assets/7689103/11872803/8dead31e-a4d7-11e5-8d51-4649daf90839.png)

And here from cmd:
![image](https://cloud.githubusercontent.com/assets/7689103/11872829/b69cbaca-a4d7-11e5-884e-fde104ed3d12.png)

Should I worry about them?

**Comment by mwrock** [comment]
It depends on what is being installed. Some packages like sql server or visualstudio may report an errorcode signifying that a reboot is needed to complete the installation. Boxstarter will try to catch these, reboot and then reattempt the install. However, it could also mean something is fundamentally wrong with that install. So it depends on the exit code and what software is reporting it.

**Comment by MNie** [comment]
I try to install several apps on machine and as I can see the installation of for example fiddler/chrome went good. But I also noticed that for example Visual Studio had not been installed at all..

**Comment by mwrock** [comment]
which visual studio package are you installing? And are you add ing any switches when instaling it?

**Comment by MNie** [comment]
Here is how my command to install visual studio looks like:

cinst VisualStudio2013Professional -y -InstallArguments "/Features:'WebTools'"

**Comment by mwrock** [comment]
hmm. you might check the vs install log in the temp directory for clues as to why it is not installing.

**Comment by MNie** [comment]
Ok, I found the issue. I'm blind so I didn't noticed that vs was already installed.. Sorry for the problem and one more time big thanks for a very fast resolve of a problem with web installer!

**Comment by mwrock** [comment]
Ah. great to hear its resolved.
