### ISSUE TITLE
Issue calling "choco install" using --source=URL syntax

### ISSUE THREAD

**Issue by labrown** [mwrock/boxstarter#145]
Greetings,

Using boxstarter 2.6.25 I just ran into an issue with boxstarter and a packer build based on mwrock-packer-templates. I call package.ps1 using this command in boxstarter.ps1:

    Install-BoxstarterPackage -PackageName a:\package.ps1 -Credential $cred
and have this line in package.ps1:

    choco install -y local-puppet --source=http://choco01.EXAMPLE.COM/chocolatey -ia 'PUPPET_AGENT_STARTUP_MODE=Manual'
which fails.  The repo source URL isn't passed correctly when boxstarter intercepts the "choco install" call.  I changed the command to:

    choco install -y local-puppet --s http://choco01.EXAMPLE.COM/chocolatey -ia 'PUPPET_AGENT_STARTUP_MODE=Manual'
and it worked fine.

**Comment by mwrock** [comment]
Thanks for reporting this! The fix will be in the next release.
