### ISSUE TITLE
Boxstarter.Azure depends on Chocolatey package windowsazurelibsfornet -version 2.5

### ISSUE THREAD

**Issue by TimMurphy** [mwrock/boxstarter#152]
```
choco install Boxstarter.Azure
```

Failed on my PC with error message that `Cannot find C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.5\bin\plugins\Caching\Microsoft.WindowsAzure.StorageClient.dll`. 

The problem was caused by the fact that I had Azure SDKs 2.7 & 2.8 installed but not 2.5. Therefore I had to install 2.5 with:

```
choco install windowsazurelibsfornet -version 2.5 --allow-downgrade
```

This workaround worked for me. However I believe Boxstarter.Azure needs to be updated to use the latest Azure SDKs or search the system for the installed version. I believe the related line is

```
RequiredAssemblies = @( "$env:ProgramW6432\Microsoft SDKs\Azure\.NET SDK\v2.5\bin\plugins\Caching\Microsoft.WindowsAzure.StorageClient.dll" )
```

in `https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Azure/Boxstarter.Azure.psd1#L24`

**Comment by gep13** [comment]
@mwrock would these tests not be prone to a similar issue:

https://github.com/mwrock/boxstarter/blob/master/tests/Azure/Get-AzureVMCheckpoint.tests.ps1#L17

**Comment by mwrock** [comment]
Well the fix for this was to "hard pin" the nuspec dependency to 2.5. Using `[2.5]` in the version syntax. I did initilaly try bumping to 2.7 but it has breaking changes with different dll file name and a different API, but eventually I will need to compensate for that but will still want to pin to whatever version is used.

**Comment by gep13** [comment]
@mwrock ah, sorry, I read the intention of the change wrong.  I see what you are saying now :+1:
