### ISSUE TITLE
Spyware.Keylogger false positive?

### ISSUE THREAD

**Issue by Redsandro** [mwrock/boxstarter#154]
Windows Remix users tell me I'm spreading a virus. I guess it's a false positive. Anything you can do code-wise to circumvent this?

![image](https://cloud.githubusercontent.com/assets/1702193/13264302/cbe3524c-da6d-11e5-8132-4097449e7896.png)

**Comment by mwrock** [comment]
I'm not sure. I just emailed them to see what I can do to get removed.

**Comment by Redsandro** [comment]
Nice! 

And props for the quick response.

**Comment by mwrock** [comment]
I have to sday I am shocked at the prompt and helpfulm response from Malwarebytes. Here is the last message:
```
Hi Matt
Our team has reviewed the file and the detection will be removed in the next update in a few hours, at that time, update the database and rescan, do not use the VirusTotal engine though, it may not get updated as quickly.
```
Thanks for bringing this to my attention.

**Comment by gep13** [comment]
:+1:
