### ISSUE TITLE
Problems with CredSSP in parallel executions

### ISSUE THREAD

**Issue by fernanqv** [mwrock/boxstarter#155]
I'm using Boxstarter to install some chocolatey packages at the same time in several machines (in parallel).

At the beginning I had problems when two Boxstarter processes tried to access the log File at the same time. I've solved that issue configuring a different log file for each process.

Now, I'm experiencing a different issue also related to concurrency. When I launch Install-BoxstarterPackage to a single computer, the CredSSP works. However, if I launch several parallel tasks to run in different computers, the CredSSP Authentication fails in most of them. In the attached file you can see the Log output.

[Errorlog.txt](https://github.com/mwrock/boxstarter/files/144671/Errorlog.txt)

It seems there is a problem with the Function Enable-BoxstarterCredSSP.ps1, but I do not know how to fix it or how to avoid the execution of this fuction. 

Anyone have any ideas how I can get around this problem?

**Comment by mwrock** [comment]
Hmm. Thats not surprising. Boxstarter was not really written with concurrency in mind and when it changes credssp settings, it later reverts those changes which may stomp on other boxstarter prpcesses. One workaround would be to enable credssp on both ends if thats appropriate for your environment. Then boxstarter wont try to mess with them.

**Comment by fernanqv** [comment]
Thanks for your response. Testing the solution you proposed I've just realized which is the problem I'm experiencing and I think it is not related to the execution of Boxstarter in parallel.

It seems to be a bug in the way Boxstarter deal with the CredSSP client credentials when there are more than one DelegateComputer entry in the system before running Boxstarter. 

The resulting problem is that delegateComputer entry added by Boxstarter at the end of its execution is not valid and the previous configuration stops working.

Before running Boxstarter the CresSSP client credentials were:
`wsman/*.campus.es,wsman/*.unican.es`

While Boxstarter is running:
 `wsman/sir096.unican.es,wsman/*.campus.es,wsman/*.unican.es`

And after the execution of Boxstarter the CredSSP have change to:
`wsman/*.campus.es,*.unican.es`  (wsman/ in the second entry is missing)

The command Enable-WSManCredSSP seems to admit only a single DelegateComputer entry at a time. Thus, when a string is passed as a parameter to DelegateComputer, it is parsed as a single entry, and the wsman/ is only added at the begginig of the string.  

Changing the Line 910 of Install-BoxstarterPackage.ps1 to:

`foreach ($entryin$CredSSPStatus.PreviousCSSPTrustedHosts.Replace("wsman/","").Split(",")){ enable-wsmancredssp-roleclient-delegatecomputer$entry-force }`

it works (at least in my server).

In [CredSSP_Test.txt](https://github.com/mwrock/boxstarter/files/147187/CredSSP_Test.txt) you can see the script I used to perform the tests
