### ISSUE TITLE
Packer-compatible Invoke-Reboot

### ISSUE THREAD

**Issue by JorritSalverda** [mwrock/boxstarter#159]
I've combined Packer with Boxstarter and that works really well. I run boxstarter from packer as described in https://github.com/mwrock/boxstarter/issues/121. The only thing that still causes me issues are reboots.

For Packer it's import that winrm is stopped during a restart so it knows a restart is happening. The Windows Restart Provisioner does this by executing the following command (see https://www.packer.io/docs/provisioners/windows-restart.html):

`shutdown /r /c "packer restart" /t 5 && net stop winrm`

Is it possible to do this during Invoke-Reboot? Or does Invoke-Reboot already do it and is it failing because of the way I run Boxstarter from Packer?

**Comment by mwrock** [comment]
Hmm. Not really. That would break boxstarter remote installs. Regarding Boxstarter and packer, I find it best to run boxstarter from a script kicked off from the AutoUnattend.xml before provisioning and have the very last thing that script does is enable winrm. This way boxstarter and packer don't "step on eachother". Ill have it run stuff here that I know is subject to reboots or does not play nice with winrm.

Then I'll put "safer" script in packer provisioners that runs without boxstarter and that I know wont need reboots.

**Comment by mwrock** [comment]
See this template: https://github.com/mwrock/packer-templates/blob/master/vbox-2012r2.json and its scripts as an example.
