### ISSUE TITLE
File, chocolatey.dll, has a different computed hash than specified in manifest

### ISSUE THREAD

**Issue by MichaelPereira** [mwrock/boxstarter#161]
Hi,

First of all, thank you for all your work on this project, it's amazing to have such capabilities now :+1: 

While trying to configure my Windows7 machine using the following gist https://gist.github.com/MichaelPereira/9f6ec55502c65691991d8f4998a94e8e later copied to `c:\gistfile1.txt`, I run into the following error shortly after the first picture:
![image](https://cloud.githubusercontent.com/assets/431374/14177523/a865817c-f724-11e5-9aa3-781e43e6662e.png)

![image](https://cloud.githubusercontent.com/assets/431374/14176840/2d3b93ae-f721-11e5-96ec-a69c1c330a1d.png)

The detailed log with the real error is below:

> PLATFORM VERSION INFO
> 	Windows 			: 6.1.7601.65536 (Win32NT)
> 	Common Language Runtime 	: 4.0.30319.42000
> 	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
> 	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
> 	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
> 	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)
> 
> SOURCES
> 	Deployment url			: http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=c:%5Cgistfile1.txt&c:%5Cgistfile1.txt
> 						Server		: Microsoft-IIS/8.0
> 						X-Powered-By	: ASP.NET
> 	Application url			: http://boxstarter.org/launch/Application%20Files/Boxstarter.WebLaunch_2_6_41_0/Boxstarter.WebLaunch.exe.manifest
> 						Server		: Microsoft-IIS/8.0
> 						X-Powered-By	: ASP.NET
> 
> IDENTITIES
> 	Deployment Identity		: Boxstarter.WebLaunch.application, Version=2.6.41.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil
> 	Application Identity		: Boxstarter.WebLaunch.exe, Version=2.6.41.0, Culture=neutral, PublicKeyToken=4b037e62ccd024b7, processorArchitecture=msil, type=win32
> 
> APPLICATION SUMMARY
> 	* Online only application.
> 	* Trust url parameter is set.
> ERROR SUMMARY
> 	Below is a summary of the errors, details of these errors are listed later in the log.
> 	* Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=c:\gistfile1.txt&c:\gistfile1.txt resulted in exception. Following failure messages were detected:
> 		+ File, chocolatey.dll, has a different computed hash than specified in manifest.
> 
> COMPONENT STORE TRANSACTION FAILURE SUMMARY
> 	No transaction error was detected.
> 
> WARNINGS
> 	There were no warnings during this operation.
> 
> OPERATION PROGRESS STATUS
> 	* [3/30/2016 4:11:22 PM] : Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?noreboot=1&package=c:\gistfile1.txt&c:\gistfile1.txt has started.
> 	* [3/30/2016 4:11:24 PM] : Processing of deployment manifest has successfully completed.
> 	* [3/30/2016 4:11:24 PM] : Installation of the application has started.
> 	* [3/30/2016 4:11:25 PM] : Processing of application manifest has successfully completed.
> 	* [3/30/2016 4:11:29 PM] : Found compatible runtime version 2.0.50727.
> 	* [3/30/2016 4:11:29 PM] : Detecting dependent assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil using Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
> 	* [3/30/2016 4:11:29 PM] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
> 	* [3/30/2016 4:11:29 PM] : Request of trust and detection of platform is complete.
> 
> ERROR DETAILS
> 	Following errors were detected during this operation.
> 	* [3/30/2016 4:11:52 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
> 		- File, chocolatey.dll, has a different computed hash than specified in manifest.
> 		- Source: System.Deployment
> 		- Stack trace:
> 			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
> 			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
> 			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
> 			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
> 			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
> 			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> 			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
> 

I tried looking into the source code to find if there was a saved hash somewhere but I couldn't find it. Could it be that the web part is not up-to-date with the new chocolatey support that went into #122?

Note: there was a chocolatey install on the computer that I removed following the instructions on https://github.com/chocolatey/choco/wiki/Uninstallation before using boxstarter. I also retried after reinstalling chocolatey with the same error.
Thanks

**Comment by mwrock** [comment]
Hmm. This actually is unrelated to your gist but is an issue with the boxstarter installer. This error is typically due to either a corrupted download or something in your environment that may be corrupting the downloaded bits. Could possibly be an antivirus in the way. Any standard antivirus should not be an issue but others have reported this with more aggressive corporate AV software.

Try reinstalling or installing on another computer preferably on a different network not governed by a corporate AV policy.

**Comment by MichaelPereira** [comment]
You were right, this was caused by the corporate firewall blocking the download. For reference, this is the signature that needed to be disabled by the system administrator in order for the download to complete:

`Gateway Anti-Virus Alert: MalAgent.H_3472 (Trojan) blocked.`

Thanks for your help
