### ISSUE TITLE
Invalid namespace error since v2.8.0

### ISSUE THREAD

**Issue by JorritSalverda** [mwrock/boxstarter#172]
After upgrading boxstarter from v2.6.41 to v2.8.0 my packer build fails with an **invalid namespace** error even though the boxstarter package itself is successfully installed.

```
Chocolatey installed 1/1 package(s). 0 package(s) failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[PACKER-57137FAB]+ Boxstarter finished Calling Chocolatey to install temp_BoxstarterPackage. This may take several minutes to complete... 00:00:48.5624657
[PACKER-57137FAB]Boxstarter: Restore Automatic Updates from Windows Update
True

Errors       : {Invalid namespace }
ComputerName : localhost
Completed    : True
FinishTime   : 4/17/2016 12:26:18 PM
StartTime    : 4/17/2016 12:25:26 PM
```

I run the following inline powershell in my packer build:

```
"inline": [
	"$ErrorActionPreference = \"Stop\"",
	"$env:chocolateyVersion = \"0.9.9.12\"",
	"iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
	"cinst boxstarter -y -version 2.8.0",
	"& \"${env:AppData}\\Boxstarter\\BoxstarterShell.ps1\"",
	"Import-Module \"$($Boxstarter.BaseDir)\\Boxstarter.Common\\boxstarter.common.psd1\"",
	"$secpasswd = ConvertTo-SecureString \"{{user `winrm_password`}}\" -AsPlainText -Force",
	"$credential = New-Object System.Management.Automation.PSCredential (\"{{user `winrm_username`}}\", $secpasswd)",
	"Create-BoxstarterTask $credential",
	"$result = Install-BoxstarterPackage -PackageName c:\\packerfile.ps1 -DisableReboots",
	"Remove-BoxstarterTask",
	"$result",
	"if ($result.Errors.Length -gt 0) { exit 1 }",
	"c:\\packerfile.post.ps1",
	"c:\\sysprep.ps1"
]
```

**Comment by JorritSalverda** [comment]
It turns out it's unrelated to the upgrade, still investigating what causes it.

**Comment by mwrock** [comment]
Anything in the boxstarter log?

**Comment by JorritSalverda** [comment]
Still trying to get the boxstarter.log from the machine - it's deleted automatically in case of failure - but i found it to be working if I pin all the boxstarter dependencies (boxstarter.common, etc) to 2.7.0. Although I pin the boxstarter chocolatey package version it did fetch the latest version for the dependencies. Going to try and bump them to 2.8.0 one by one to find which package causes the error. At the same time I'll try and get the log file.

**Comment by JorritSalverda** [comment]
Things go wrong as soon as I set boxstarter.bootstrapper v2.8.0 (common and winconfig are fine to set to 2.8.0). The only thing related to namespaces I can find is the following https://github.com/mwrock/boxstarter/search?utf8=%E2%9C%93&q=invalid+namespace, but that's in the wrong package. Were there any changes to bootstrapper that could cause this? The boxstarter.log doesn't seem to provide any actionable information, but I'll tidy it up and add it later.

**Comment by mwrock** [comment]
I'm betting its this commit: https://github.com/mwrock/boxstarter/commit/b3193a6c5a5a530822386261b4db823cbdefc10b#diff-cbc2ad1b6dd0488d34c0b5671b0091fbR121

likely line 162. I tested his on 2012R2 and 2k8r2. Just curious what OS are you building?

**Comment by JorritSalverda** [comment]
I'm using Google Cloud image windows-server-2012-r2-dc-v20160413.

**Comment by JorritSalverda** [comment]
One thing that doesn't help - but might not be the cause - is that `$ComputerName="$env:COMPUTERNAME"` truncates the computer name.

**Comment by mwrock** [comment]
On my work laptop (win 10) I am able to reproduce this:
```
C:\dev\chef-provisioning-vsphere [master ↑]> $CCMSplat = @{
>>         NameSpace='ROOT\ccm\ClientSDK'
>>         Class='CCM_ClientUtilities'
>>         Name='DetermineIfRebootPending'
>>         ComputerName='localhost'
>>         ErrorAction='Stop'
>>     }
C:\dev\chef-provisioning-vsphere [master ↑]> Invoke-WmiMethod @CCMSplat
Invoke-WmiMethod : Invalid namespace
At line:1 char:1
+ Invoke-WmiMethod @CCMSplat
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-WmiMethod], Manage
   mentException
    + FullyQualifiedErrorId : InvokeWMIManagementException,Microsoft.PowerShel
   l.Commands.InvokeWmiMethod
```

**Comment by mwrock** [comment]
should be a pretty easy fix.

**Comment by JorritSalverda** [comment]
Cool thanks. Do you have pre-release packages on chocolatey through which I could verify a fix?

**Comment by mwrock** [comment]
I don't typically post prereleases. This particular bug looks easily reproducable and I may be able to get a release out tonight.

**Comment by riezebosch** [comment]
I [commented](https://github.com/mwrock/boxstarter/commit/b935beeea2f8c21f7162b7a44aad97f73fd4dfc7#commitcomment-17253392) on the commit because it seems to break my pending reboot when trying to install Visual Studio 2015 Enterprise on my Windows Server 2012 R2 machine.

**Comment by mwrock** [comment]
ugh. I have a fix [here](https://github.com/mwrock/boxstarter/commit/53ee14834d6c9e1938559cffb688a92642f08f94) but want to add a test to insure this does not regress again. Hope to get a release out tonight.

**Comment by mwrock** [comment]
its now released thanks to the help of @riezebosch
