### ISSUE TITLE
Packer run fails when installing WMF 5.0

### ISSUE THREAD

**Issue by ryanl-ee** [mwrock/boxstarter#182]
Hi Matt,

First of all thanks so much for the work you've done with Chef/Packer/Windows! It has been incredibly useful.

I'm running into an issue where if I add this one line to my Boxstarter `package.ps1` script:
```
if($psversiontable.PSVersion.Major -ne 5){ cinst powershell -y; Invoke-Reboot }
```
or even just `cinst powershell-y`, Boxstarter will finish its script with `Type ENTER to exit` after enabling WinRM. As part of my provisioner Powershell script I clean up Boxstarter and Chocolatey, but since Chocolatey is still running, it fails with permission denied. It looks like that `Read-Host` is coming from https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Cleanup-Boxstarter.ps1#L38, but I'm not sure why it's pausing & asking for input. If I remove the `cinst powershell` line, everything works fine and I don't get asked for input. I'll try killing Chocolatey as part of the cleanup process but just thought this was weird.

**Comment by mwrock** [comment]
Hey I'm glad you find all of this useful!

If boxstarter reboots the machine, its normal for the prompt to display at the end of a boxstarter run. This typically isn't a problem if running boxstarter from a script that's kicked off fro an answer file "run once" action in packer because packer just launches the provisioners after winrm starts up.

Are you seeing this halt the entire process? And does it occur even if the machine never reboots during the boxstarter run?

**Comment by ryanl-ee** [comment]
Yup, that's all accurate - I am running Boxstarter as part of the answer file, then the provisioner from Packer. It doesn't happen if it doesn't reboot and it doesn't halt the process, but since I want to clean up Boxstarter/Chocolatey/etc. as part of the Packer provisioner script, and the Boxstarter prompt is still open, the files can't be deleted. Is there a way to override this behavior? Or is there a way for Boxstarter to clean itself up afterwards? Thanks!

**Comment by mwrock** [comment]
There realy isn't a clean way to close the window in this scenario. The best you could do is find the powershell process hosting boxstarter and kill it in your provisioner. That may be as simple as:
```
Stop-Process | (Get-Process -Name Powershell | ? { $_.id -ne $PID })
```
Which would kill all powershell processes other than the one issuing this command.

**Comment by ryanl-ee** [comment]
Thanks! That worked. I had to use `Get-Process Powershell | Where-Object { $_.ID -ne $PID } | Stop-Process` but was able to clean up at the end of the run.
