### ISSUE TITLE
Return information (like failed packages) from the initial START command - possible?

### ISSUE THREAD

**Issue by Redsandro** [mwrock/boxstarter#195]
I'm not sure about the possibilities, and how different events are chained. I'm assuming something like this:

* `START boxstarter_script.Application`
* `if not exists` Boxstarter
  * Install Boxstarter
* `if not exists` Chocolatey
  * Install Chocolatey
* execute `boxstarter_script.Application` payload
  * execute Chocolatey in batch
* _Press ENTER to exit_

Is it possible to communicate something back to the `dotNET` application that started the process?

* Does the exit code from the `START` command relate to the success of Chocolatey?
* Can we return more than the exit code?
  * Can we return the package id`s from the failed pacakges, so we can notify the host?
    * E.g. I could let [WindowsRemix](http://www.windowsremix.com) alert on these packages and only remove the succesfully installed ones from the queue.

I'll probably be releasing a beta version of the site in a couple of months. Some much needed stability fixes. If boxstarter could somehow communicate back in the same process, it would open up a lot of possibilities.

**Comment by mwrock** [comment]
The click once URL is pretty limited. It's designed to simply invoke an app install and run. The best way to interact with boxstarter is to use the boxstarter powershell modules instead of the web launcher URL.

**Comment by Redsandro** [comment]
I can probably only do this through my ClickOnce helper for Chrome, since it's C#. Not sure I can do the same with Firefox. Probably not with Internet Explorer and Edge. Do you know anything about IE/Edge communicating with PS?

Also, can I run boxstarter posh modules by executing an .exe file? I think I can hook into rundll32.exe from Firefox.

I'd be interested to see if I can get some system information on the website this way, and possibly read/change some system settings through boxstarter.

Also, imagine I know nothing about boxstarter apart from how to batch-install packages. Do you know of any boxstarter module(s) for me to look at that might be relevant to my interests?

Sorry for the many questions.

**Comment by mwrock** [comment]
> Do you know anything about IE/Edge communicating with PS?

Afraid not.

> can I run boxstarter posh modules by executing an .exe file?

You can invoke powershell.exe and import the boxstarter modules via the `-command` param or via a script file through `-file`

**Comment by Redsandro** [comment]
Thanks.
