### ISSUE TITLE
Running a build script from an http source

### ISSUE THREAD

**Issue by deckerjohn** [mwrock/boxstarter#199]
Errors       : {Exception calling "Run" with "1" argument(s): "Cannot combine a path with ':' attempted to combine 
               'http:\\boxname.corp.com\boxstarter.txt' with 'C:\ProgramData\chocolatey\lib-bkp'"}

Hello,

This might be an easy one for someone but I'm a novice and my build scripts run fine from a local source c:\ drive but when I try to host them from an http source they fail   What am I doing wrong.  Is there a certain restriction in declarations for an http: source?   Very simple commands seem to work ok

**Comment by mwrock** [comment]
can you provide an example of a command where you are using an http source?

**Comment by deckerjohn** [comment]
Install-BoxstarterPackage -ComputerName FQDN  -PackageName http:\FQDN\Boxstarter.txt -Credential $cred

I've tried quotes around packagename with no effect

**Comment by mwrock** [comment]
oh i see. you want `http://` instead of `http:\` and make sure all slashes are forward slashes.

**Comment by deckerjohn** [comment]
Sorry...well you have your dumbass user story for the day at least

aplogies for the typo

**Comment by mwrock** [comment]
Hey no prob. Sometimes you just need a second pair of eyes to find those typos

**Comment by mwrock** [comment]
Hey no prob. Sometimes you just need a second pair of eyes to find those typos
