### ISSUE TITLE
Get-ADcomputer or WSUS calls from inside a boxstarter session

### ISSUE THREAD

**Issue by deckerjohn** [mwrock/boxstarter#200]
Hello,

I'm wondering if anyone knows or has seen problems either doing Get-Adcomputer -prop description or doing a WSUS call like the following:
 $wsus = [Microsoft.UpdateServices.Administration.AdminProxy]::getUpdateServer($wsusserver,$False)

When performing a build from a remote call?   The same code runs great when you do a local boxstarter build with the URL/WebApp

I know I can potentially just re-arrange my script and run that code from the initiating machine but I was preferring to have that code successfully logged in the boxstarter log for the server somehow so that it could be reviewed.    Is situations like this a case where you would use Invoke-BoxstarterTask?

Thanks for anyones help/input/suggestions

**Comment by mwrock** [comment]
I'm not 100% certain about `Get-Adcomputer` but I am certain wsus APIs do not work repotely. Boxstarters `Install-WindowsUpdate` gets around that by running inside of a scheduled task on remote machines. You could look at using [`Invoke-FromTask`](https://github.com/mwrock/boxstarter/blob/master/BoxStarter.Common/Invoke-FromTask.ps1) for this.
