### ISSUE TITLE
Invoke-Fromtask and Get-IIsremote

### ISSUE THREAD

**Issue by deckerjohn** [mwrock/boxstarter#201]
Hello,

Im trying to call these two functions from inside my build script but its not finding them.   Is there something else I need to import ?  Cannot quite find an example out there unless I'm going about it all wrong.  Chocolatey seems to function fine otherwise.

Thanks

**Comment by mwrock** [comment]
I apologize. I should have shown you how to call those. They are currently not exposed by default So you have to import the Boxstarter.Common module and als make sure to create the task:
```
$secpasswd = ConvertTo-SecureString "vagrant" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ("vagrant", $secpasswd)
Create-BoxstarterTask $Credential
Invoke-FromTask "your script"
Remove-BoxstarterTask
```

With the Boxstarter.Common module imported, you also have access to the Get-IsRemote command.

**Comment by deckerjohn** [comment]
Hey, thanks again I really appreciate it, I've only been coding really for about a year so I dont always pick what I should readily.  I'd love to see my company use Boxstarter as sort of a platform agnostic last mile cloud delivery solution to help with saving developers time.   I'd love to see us move to more of an Infrastructure as Code model and start delivering a tier at a time rather than a box at a time.  Every line written is another line closer
