### ISSUE TITLE
$boxstarter.NoPassword=$True is not working, or I don't understand how it's supposed to work

### ISSUE THREAD

**Issue by flatlinebb** [mwrock/boxstarter#210]
I'm trying to use the variable $boxstarter.NoPassword=$True on a system that has no password and it boots to the Win7 desktop automatically for convenience. When I pass this option in a gistfile, it stops and prompts me for a password. And if I supply a blank password, bu hitting ENTER 3 times, it then disabled auto-reboot, which defeats the purpose of being able to run maintenance unattended on this machine. I want to upgrade all choco packages, install all critical Windows Updates and reboot as many times as necessary until the process is complete.

Here is my gist file: 
https://gist.github.com/flatlinebb/309ee785c90f12514aceb4689d806529

**Comment by dragon788** [comment]
Not sure if the case matters, but that is the one line using $boxstarter instead of $Boxstarter.

**Comment by flatlinebb** [comment]
The case makes a difference it seems. It's working for me now.
