### ISSUE TITLE
Chocolatey outdated. Packages failing. Update to choco.

### ISSUE THREAD

**Issue by Redsandro** [mwrock/boxstarter#225]
:warning: The `posh` version of `chocolatey` included with `boxstarter` is outdated, and a lot of non-trivial are failing because of it.

One of the reasons this is happening is checksum verification. I believe `chocolatey` always uses `md5` checksums even when the packages require `sha256` checksums, which are supported in `choco`.

Some packages failing with `boxstarter` but installing correctly using the latest `choco` are:

* `GoogleChrome`
* `mpc-hc`
* `octave.portable`

Could you find a way to start using the new `choco` @mwrock?

**Comment by mwrock** [comment]
Boxstarter moved off the posh version some time ago but it is bundling an outdated choco.dll that was released prior to the current checksum behavior. Unfortunately the more recent versions break fundamental boxstarter compatibility and I am waiting for https://ci.appveyor.com/project/chocolatey/choco/build/1.0.0.1121/artifacts to be released.

**Comment by Redsandro** [comment]
> Boxstarter moved off the posh version some time ago

Oops, sorry! I thought wrong.

> I am waiting for **(GH-1041) Fix bad PowerShell script** to be released.

Judging from the name, it's about this: https://github.com/chocolatey/choco/issues/1041

I understand the problem with the typo, but apart from that the system really is wizardry to me. Priority seems high enough on that one though. So I'll remain blissful. :)

**Comment by Redsandro** [comment]
@mwrock are the recently released 0.10.4 and 0.10.5 fixing any of the issues you are seeing with the new checksums?

**Comment by mwrock** [comment]
Yes. Shouldn't have checksum issues anymore
