### ISSUE TITLE
Boxstarter creating nested chocolatey dirs under LocalAppData\Temp

### ISSUE THREAD

**Issue by KZeronimo** [mwrock/boxstarter#243]
I'm launching Boxstarter from the web with a [Gist](https://gist.github.com/KZeronimo/ebf52afab747141f691688e6c321c3c5) - all is working well now

I did have to hack around on the order of the chocolatey install commands (for example - I had to move `cinst sql-server-management-studio` up - so I went ahead and put it first) to get things working.  The only thing I can conjecture is the depth of the chocolatey dirs and maybe something in the installer can't handle the depth

> C:\<LocalAppData>\Temp\chocolatey\chocolatey\...\chocolatey

I can repro and attach logs if that would be helpful; otherwise, wondering if this sort of thing happens - is the nested chocolatey dirs expected

**Comment by mwrock** [comment]
This is a dupe of #241 and awaiting a fix in chocolatey
