### ISSUE TITLE
Boxstarter Install-WindowsUpdate doesn't install all available updates

### ISSUE THREAD

**Issue by mwallner** [mwrock/boxstarter#246]
When using default/no criteria, `Install-WindowsUpdate` differs from the default Windows update behavior.
it looks like hardware-specific updates are skipped - probably because of the `criteria` ? https://github.com/mwrock/boxstarter/blob/master/Boxstarter.WinConfig/Install-WindowsUpdate.ps1#L29

Here's a demo of Install-WindowsUpdate vs. installing updates manually on the same machine, right after setup:
* [WindowsUpdates.Boxstarter.txt](https://github.com/mwrock/boxstarter/files/903830/WindowsUpdates.Boxstarter.txt)
* [WindowsUpdates.WindowsUpdate.txt](https://github.com/mwrock/boxstarter/files/903831/WindowsUpdates.WindowsUpdate.txt)

can the criteria be altered, in a way that _ALL_ updates, will be installed through boxstarter?

**Comment by dragon788** [comment]
Have you tried using `Install-WindowsUpdate -AcceptEula` to get some of the updates that require a license acceptance?

**Comment by mwallner** [comment]
Thanks! - will try and give feedback asap

**Comment by dragon788** [comment]
I should also note on the last one, you may want to add the `-AcceptEula` as well in order to get the maximum number of updates since odds are a few out of "everything" will require a license agreement.

**Comment by mwallner** [comment]
`Install-WindowsUpdate -Criteria "IsInstalled=0" -AcceptEula` skipped the driver updates:
[WindowsUpdatesBoxstarterIsInstalled0.txt](https://github.com/mwrock/boxstarter/files/912371/WindowsUpdatesBoxstarterIsInstalled0.txt)

Anything else I can try other than specifying the `Type` in `-Criteria` manually? (how are the odds Microsoft will change the available types - and is there even a list of those somewhere?)

**Comment by mwrock** [comment]
Not alot of documentation on the criteria string. https://msdn.microsoft.com/en-us/library/windows/desktop/aa386526%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 is worth a look. I'd try adding `Type='Driver'` as @dragon788 suggested above.

**Comment by mwallner** [comment]
having multiple types in a criteria string isn't working - the obvious way to go is to split up the update process into two tasks - i.e. first one with `Type='Software'`, second one with `Type='Driver'`

~ thanks for your suggestions!
