### ISSUE TITLE
`Read-Host` prompts are timed

### ISSUE THREAD

**Issue by C-Duv** [mwrock/boxstarter#253]
Since I upgraded from v2.8.29 to v2.9.5, my uses of `Read-Host` are timed: the following warning message is displayed:
> Respond within 30 seconds or the default selection will be chosen

Example code:
```PowerShell
Read-Host 'Run entire process? (y/n) [default:yes]'
```

Resulting output:
```
Read-Host 'Run entire process? (y/n) [default:yes]'
  Confirmation (`-y`) is set.
  Respond within 30 seconds or the default selection will be chosen.
```

Does Boxstarter overrides default PowerShell `Read-Host`? Can it be configured to allow longer delay? Infinite?

**Comment by mwrock** [comment]
Hmm. Boxstarte does not override Read-Host at all. Its possible this is something happening inside of chocolatey. I have never seen this but I don't have any packages using read-host.

**Comment by Skolzack** [comment]
It's from Chocolatey I think. I searched around but didn't find any solutions to make it longer. @ferventcoder Can you help? For me, I want to remove the timeout of read-host.

**Comment by ferventcoder** [comment]
@C-Duv fllow this issue - https://github.com/chocolatey/choco/issues/757

**Comment by C-Duv** [comment]
How can it be coming from Chocolatey?
I run script with:
```Batch
BoxStarter.bat MyBoxstarterPackageName -DisableReboot
```
And my `Read-Host` are way before any `choco` command.

Trying to run:
```Batch
BoxStarter.bat MyBoxstarterPackageName -DisableReboot --use-system-powershell
```
gives me a *The package was not found with the source(s) listed.* error. See full log:

    Boxstarter: Installing package MyBoxstarterPackageName
    Boxstarter Version 2.9.5
    (c) 2016 Matt Wrock. http://boxstarter.org
    
    Boxstarter: Disabling Automatic Updates from Windows Update
    + Boxstarter starting Calling Chocolatey to install MyBoxstarterPackageName. This may take several minutes to complete...
    Installing the following packages:
    MyBoxstarterPackageName
    By installing you accept licenses for the packages.
    MyBoxstarterPackageName not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""
     Source(s): "D:\boxstarter\--use-system-powershell;http://chocolatey.org/api/v2;http://www.myget.org/F/boxstarter/api/v2"
    
    Chocolatey installed 0/1 packages. 1 packages failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    
    Failures
     - MyBoxstarterPackageName - MyBoxstarterPackageName not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""
     Source(s): "D:\boxstarter\--use-system-powershell;http://chocolatey.org/api/v2;http://www.myget.org/F/boxstarter/api/v2"
    + Boxstarter finished Calling Chocolatey to install MyBoxstarterPackageName. This may take several minutes to complete... 00:00:04.2951519
    Boxstarter: Restore Automatic Updates from Windows Update
    True

If I run:
```Batch
BoxStarter.bat -DisableReboot --use-system-powershell MyBoxstarterPackageName
# Or
BoxStarter.bat --use-system-powershell MyBoxstarterPackageName -DisableReboot
```

BoxStarter tries to install the `--use-system-powershell` package as shown in the following logs:

    Boxstarter: Installing package --use-system-powershell
    Boxstarter Version 2.9.5
    (c) 2016 Matt Wrock. http://boxstarter.org
    
    Boxstarter: Disabling Automatic Updates from Windows Update
    + Boxstarter starting Calling Chocolatey to install --use-system-powershell. This may take several minutes to complete...
    Exception lors de l'appel de « Run » avec « 1 » argument(s) : « Package name is required. Please pass at least one package name to install. »
    + Boxstarter finished Calling Chocolatey to install --use-system-powershell. This may take several minutes to complete... 00:00:03.4527424
    Boxstarter: Restore Automatic Updates from Windows Update
    True

Is there something wrong with my package or run command?

**Comment by mwrock** [comment]
Boxstarter converts your script into a chocolatey package. So the entire script is run from chocolatey.

**Comment by C-Duv** [comment]
Oh... This explains that :)

So what's the correct way to use `--use-system-powershell` when running my Boxstarter package from `BoxStarter.bat`?

**Comment by mwrock** [comment]
Boxstarter does not support passing that option to the top level package it creates.
