### ISSUE TITLE
Boxstarter doesn't run automatically after reboot unless I log in

### ISSUE THREAD

**Issue by illectronic** [mwrock/boxstarter#258]
I am calling it like this:

 Install-BoxstarterPackage -PackageName C:\deployment\Scripts\script.ps1

It reboots but I'm not sure it does anything when it comes back up unless I log in again. If I log in again it starts the script again and everything works. How do I get it to continue on boot without logging in again?

**Comment by mwrock** [comment]
You need to give `Install-BoxstarterPackage` credentials via the `-Credentials` argument. It will then use those credentials to lo in on reboot.

**Comment by illectronic** [comment]
Thanks. I am trying to automate installation of Windows features on boot in AWS. Do I need to set the default "Administrator" password or is a way I can run the boxstarter script as another user so it logs in using the user in the -credential rather than the user I ran it as.

**Comment by illectronic** [comment]
Sorry I think I see why. I should be using: $cred=Get-Credential mwrock and NOT the pscredentials?

**Comment by illectronic** [comment]
Looks like pscredential worked. Closing this.
