### ISSUE TITLE
Cannot Start Application - Application Validation Did Not Succeed

### ISSUE THREAD

**Issue by UnkleFeSSSter** [mwrock/boxstarter#261]
This had been working up to last week.   But then this week the webstarter download gets to 18.8 of 18.9MB and then errors. In the log it points to:

Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?package=z:\Boxstarter\server.ps1&z:\Boxstarter\server.ps1 resulted in exception. Following failure messages were detected:
		+ File, Boxstarter.Chocolatey.psd1, has a different computed hash than specified in manifest.

There is no AV or Firewall blocking the download.  I've attached the log file.

Any help would be greatly appreciated.

Thanks
[7FBBM1H9.txt](https://github.com/mwrock/boxstarter/files/1042679/7FBBM1H9.txt)

**Comment by mwrock** [comment]
Just fixed this and my apologies for this.
