### ISSUE TITLE
{Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Users\Boxstarter\AppData\Roaming\boxstarter\boxstarter.chocolatey\chocolatey\AlphaFS.dll' because it does not exist."}

### ISSUE THREAD

**Issue by kastis77** [mwrock/boxstarter#263]
Hi, after executing 
Install-BoxstarterPackage -PackageName C:\Scripts\ip.ps1 -Credential $cred
receving this error. Maybe someone knows to what this error is related (missing AlphaFS.dll file)? In location 'C:\Users\Boxstarter\AppData\Roaming\Boxstarter\Boxstarter.Chocolatey\chocolatey' there is no such file.

### Boxstarter: Installing package C:\Scripts\ip.ps1
Boxstarter Version 2.9.24
(c) 2017 Matt Wrock. http://boxstarter.org

Boxstarter: Disabling Automatic Updates from Windows Update
Boxstarter: Restore Automatic Updates from Windows Update

Errors       : {Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
               'C:\Users\Boxstarter\AppData\Roaming\boxstarter\boxstarter.chocolatey\chocolatey\AlphaFS.dll' because
               it does not exist."}
ComputerName : localhost
Completed    : False
FinishTime   : 6/19/2017 12:13:02 PM
StartTime    : 6/19/2017 12:13:02 PM

% : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
'C:\Users\Boxstarter\AppData\Roaming\boxstarter\boxstarter.chocolatey\chocolatey\AlphaFS.dll' because it does not
exist."
At C:\Users\Boxstarter\AppData\Roaming\boxstarter\Boxstarter.Chocolatey\invoke-chocolatey.ps1:8 char:13
+     $refs | % {
+             ~~~
    + CategoryInfo          : WriteError: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by kastis77** [comment]
p.s. Boxstarter Chocolatey Module 2.9.24 missing AlphaFS.dll (Boxstarter Chocolatey Module 2.9.14  has it). 
If i copy manualy works without error. invoke-chocolatey.ps1 has link to this file
function Invoke-Chocolatey($chocoArgs) {
    Write-BoxstarterMessage "Current runtime is $($PSVersionTable.CLRVersion)" -Verbose
    $refs = @( 
        "$($Boxstarter.BaseDir)/boxstarter.chocolatey/chocolatey/log4net.dll",
        "$($Boxstarter.BaseDir)/boxstarter.chocolatey/chocolatey/chocolatey.dll",
        "$($Boxstarter.BaseDir)/boxstarter.chocolatey/chocolatey/AlphaFS.dll"

**Comment by mwallner** [comment]
can confim this:
![image](https://user-images.githubusercontent.com/5354972/27291418-6fe6b0d2-5510-11e7-956e-4094cfae62de.png)

vs 2.9.14 (has AlphaFS)
![image](https://user-images.githubusercontent.com/5354972/27291483-99415f90-5510-11e7-93b1-dbaa5d1c70b1.png)

**Comment by mwrock** [comment]
My apologies. Fix is incoming for this.

**Comment by mwrock** [comment]
ok 2.9.26 is now released fixing this.
