### ISSUE TITLE
TMP Issue

### ISSUE THREAD

**Issue by Skolzack** [mwrock/boxstarter#274]
Hello guys,

i'm quite new using Boxstarter but I want a little help or maybe a bug, idk. I'm trying to run my script https://gist.githubusercontent.com/Skolzack/fddce56392c094d790d9ebeadabfefb2/raw/56a08ee56c67d96c0a13ede3e4cd4f17d837ac30/Boxstarter.Testing.ps1 and it give me error on TMP.

_Boxstarter log_: 

> **ERROR: The term 'cinstm' is not recognized as the name of a cmdlet, function,  file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1';& Import-Module 'C:\Users\rafae\AppData\Local\Apps\2.0\LT3Y0ERV.4A9\PJ7K626Q.LCW\boxs..tion_6b092740f7261cd0_0002.0009_8212bec7b6369c95\Boxstarter.chocolatey\Boxstarter.chocolatey.psd1' -DisableNameChecking -ArgumentList $true; & 'C:\ProgramData\chocolatey\helpers\chocolateyRunner.ps1' -package 'C:\ProgramData\chocolatey\lib\tmp80F3.tmp\tools\ChocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.**

_CMD log_:

>  ERROR: The term 'cinstm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> The install of tmp9f08.tmp was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\tmp9F08.tmp\tools\ChocolateyInstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - tmp9f08.tmp (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\tmp9F08.tmp\tools\ChocolateyInstall.ps1'.
>  See log for details.
> 
> Enjoy using Chocolatey? Explore more amazing features to take your
> experience to the next level at
>  https://chocolatey.org/compare
> Chocolatey : Chocolatey reported an unsuccessful exit code of -1. See
> C:\Users\rafae\AppData\Local\Boxstarter\boxstarter.log for details.
> No C:\Users\rafae\AppData\Local\Apps\2.0\LT3Y0ERV.4A9\PJ7K626Q.LCW\boxs..tion_6b092740f7261cd0_0002.0009_8212bec7b6369c
> 95\Boxstarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:201 caractere:5
>     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

Can anyone help me to figure it out? Thanks in advance.

**Comment by ferventcoder** [comment]
Use one of the following options:

* choco install
* cinst

`cinstm` was deprecated and removed in 0.9.9 (after long term deprecation warnings to give you plenty of time to respond to deprecations before removal) - see https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#099-march-3-2015 (breaking changes):

> **Deprecated/Removed Commands**:
> * **installmissing** has been removed. It was deprecated awhile ago, so this should not be a surprise.

`choco install` behaves similar to the functionality of what `cinstm` did. If you want the latest of something, even if installed, use `choco upgrade`.

**Comment by Skolzack** [comment]
@ferventcoder I removed the 'cinstm' commands but the error persisted. I was like 'wtf?' Then I figured out that everytime when you change the code on gist the raw link changes too lol. So I need to generate a new bit.ly and I was using always the same link (i'm dumb, ikr). 

Everything worked fine now. Thanks for the fast support!

**Comment by ferventcoder** [comment]
@mwrock you can close this.
