### ISSUE TITLE
Install Windows feature via DISM that requires reboot

### ISSUE THREAD

**Issue by KZeronimo** [mwrock/boxstarter#282]
I'm currently utilizing the web start method with a gist for the Boxstarter script - 2 questions

1. I assume the web start method from PS `start http://boxstarter.org/package/nr/url?<gist>` is still acceptable as long as the default browser is Edge - looks like the [Run with Gist](http://boxstarter.org/Learn/WebLauncher) has changed slightly
2. I'm using DISM to enable Hyper-V prior to installing Docker via `DISM /Online /Enable-Feature:Microsoft-Hyper-V /All /NoRestart` - if I don't suppress the reboot with Boxstarter pickup and continue with the remainder of the package.  I would like to have the required reboot built in

**Comment by mwrock** [comment]
1. The web start method is derecated and currently uses an older version of boxstarter. The best way to get boxstarter is to use `. { iwr -useb http://boxstarter.org/bootstrapper.ps1 } | iex; get-boxstarter -Force`  and then use the `Install-BoxstarterPackage` comand to run packages.

2. If you do not suppress the reboot, boxstarter will not pick up the install after the reboot. The best way to handle this is to use chocolatey to install windows features using the `windowsfeatures` `--source` then boxstarter will reboot and restart if a reboot is required.

**Comment by KZeronimo** [comment]
Thanks Matt - just curious was the web start method deprecated because of security hoops

I'll look for your comment - feel free to close at your convenience

**Comment by mwrock** [comment]
Take a look at http://www.hurryupandwait.io/blog/retiring-the-boxstarter-web-launcher
