### ISSUE TITLE
ClickOnce Support with Deltek Ajera

### ISSUE THREAD

**Issue by wackogracko** [mwrock/boxstarter#294]
I've been using the Windows Remix ClickOnce Handler in Google Chrome for the past several years with the Deltek Ajera program. A recent update in Chrome caused this extension to stop working with Delteks ClickOnce based program. I tested in IE version 11.0.9600.18792 and it works fine there. I am on the following versions:

Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Windows Remix ClickOnce Handler 1.3.1.1
.NET Framework version 4.7.02053

I am receiving this error when trying to run the ClickOnce application:

![image](https://user-images.githubusercontent.com/34377413/33774192-a675a310-dbf7-11e7-874e-f4ebbeeeadae.png)

Any help would be greatly appreciated as I have to use this application all day everyday and being stuck in IE is miserable.

**Comment by ferventcoder** [comment]
Hi @wackogracko Windows Remix makes me think that is something different than BoxStarter - it looks like it belongs to http://windowsremix.com/ (@RedSandro)

**Comment by ferventcoder** [comment]
I'm going to preemptively close this as it looks like you are filing an issue for a different tool. Please comment if this is mistaken and we can reopen this.

**Comment by ferventcoder** [comment]
I saw your comments over at https://github.com/mwrock/boxstarter/issues/97#issuecomment-350295673 as well.

**Comment by wackogracko** [comment]
This is not directly boxstarter related but there is probably the most related knowledge here. I posted here because there was a similar recent post about ClickOnce support for Firefox

https://github.com/mwrock/boxstarter/issues/61

You are correct, this is a tool by @Redsandro, was hoping he could take a look. If there is a more relevant spot to post this let me know.

Thanks

**Comment by ferventcoder** [comment]
@wackogracko I am not sure how you would follow up to get it fixed, other than by contacting Red directly.
