### ISSUE TITLE
Win10 - ERROR: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope. 

### ISSUE THREAD

**Issue by timabell** [mwrock/boxstarter#307]
Sorry if this is me just doing something stupid but I wanted to share in case it's not just me.

Just built a clean Win10 x64 VM in VirtualBox, nothing but updates and guest additions installed.

Running my boxstarter failed with 

```
ERROR: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
The install of tmpc91.tmp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\tmpC91.tmp\tools\ChocolateyInstall.ps1'.
 See log for details.
```

This the gist https://gist.github.com/timabell/608fb680bfc920f372ac/133562a723af05b070210239838f1bad2d4ba09a (pinned to the revision I ran)

Full log: [boxstarter.log](https://github.com/mwrock/boxstarter/files/1862253/boxstarter.log)

```
PS C:\Users\tim> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```

More info (mostly for my own benefit, this stuff makes my head hurt) https://stackoverflow.com/q/27753917/10245

**Comment by timabell** [comment]
```
PS C:\Users\tim> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```

**Comment by timabell** [comment]
Oh, wait, I am an idiot. I'd commented out the execution policy line in my script but it took a while for it to be noticed. User error. Sorry to bother you.

**Comment by Vagrantin** [comment]
Thanks for sharing ! I got the same issue !
Solved the same way 👍
