### ISSUE TITLE
Errors not reported when boxstarter package reboots machine

### ISSUE THREAD

**Issue by SurajGupta** [mwrock/boxstarter#45]
Hello.  I've noticed that sometimes when a chocolatey install fails, BoxStarter does not report the error in the log file.  So if you aren't watching the console, you could miss a legitimate error.  I'm unsure if this is specific to chocolatey install failures or applies to any failure when running a BoxStarter package (e.g. custom powershell).  I was able to create this minimal test case to reproduce the error (clean/vanilla Windows 8.1 machine with all windows updates as of today)

**test.ps1**

    if ( Get-UAC )
    {
        Disable-UAC
        Invoke-Reboot
    }
    cinst nuget.commandline
    # force error by extracting to c:\windows\system32
    cinst sqlserver2014express
    cinst GoogleChrome

**execution**

    BoxstarterShell.bat
    $creds = Get-Credential
    Install-BoxstarterPackage -PackageName PATH_TO_TEST_PS1 -Credential $creds

When SQL Server is installing (sorry for the large download!), choose `c:\windows\system32\SqlServer2014ExpressInstall\` to extract files, which will force an error in the install.  Notice how the error is reported in the console.  Boxstarter continues and installs Chrome, but the error doesn't appear in the log file.  Here's the log file: https://gist.github.com/SurajGupta/307aec9b6ce00330ecff

And the console/package install session ends with the following:
    "Type ENTER to exit"

Now try a package with no reboot:

    cinst nuget.commandline
    # force error by extracting to c:\windows\system32
    cinst sqlserver2014express
    cinst GoogleChrome

The error still shows up in the console.  But now the log file shows the error.  Here's the log file: https://gist.github.com/SurajGupta/535c80ac41a40cc7f4f0

Also, the console/package install session ends with the following:

    Errors       : {Package 'SqlServer2014Express v1.0.1' did not install successfully: [ERROR] Running C:\Users\suraj\AppD
                   ata\Local\Temp\chocolatey\SqlServer2014Express\SqlServer2014ExpressInstall.exe with   was not successful
                   . Exit code was '-2147467259'., SqlServer2014Express did not finish successfully. Boo to the chocolatey
                   gods!
                   -----------------------
                   [ERROR] [ERROR] Running C:\Users\suraj\AppData\Local\Temp\chocolatey\SqlServer2014Express\SqlServer2014E
                   xpressInstall.exe with   was not successful. Exit code was '-2147467259'.
                   -----------------------, [ERROR] Running C:\Users\suraj\AppData\Local\Temp\chocolatey\SqlServer2014Expre
               ss\SqlServer2014ExpressInstall.exe with   was not successful. Exit code was '-2147467259'.}
    ComputerName : localhost
    Completed    : True
    FinishTime   : 01/06/2015 08:55:33
    StartTime    : 01/06/2015 08:47:46

So it seems that the restart somehow puts Boxstarter into a state where it does not report errors.

**Comment by mwrock** [comment]
interesting. Thanks for reporting!
