### ISSUE TITLE
Boxstarter is inconsistent about package summary

### ISSUE THREAD

**Issue by SurajGupta** [mwrock/boxstarter#46]
Please see this bug: https://github.com/mwrock/boxstarter/issues/45
Notice that in one case Boxstarter displays a nice summary message in the console after a package has completed but in another case it does not.

**Comment by mwrock** [comment]
Yes. This is a known issue. Its also something I intend to fix in the next major version of boxstarter. It involves how boxstarter structures an installation run and really isn't worth addressing in a routine bug fix release.

That said, I dont have any ETA.

Thanks for reporting though! Its good to know that others take notice of this.

**Comment by SurajGupta** [comment]
thanks, Matt!
