### ISSUE TITLE
Running Package from Boxshare returns cannot find package 'MyTestPackage'

### ISSUE THREAD

**Issue by johnkattenhorn** [mwrock/boxstarter#51]
I'm not sure if this should work so apologies if it's not designed to work this way.

I followed the instructions and issued the following command on the hostmachine

Set-BoxstarterShare BoxShare

I got a share and I can see inside the share from a remote machine no problem, there is a buildpackages directory in the shared directory but the config on the host doesn't use this one, it's redirected elsewhere.

I have a package in this LocalRepo called MyTestPackage and commands to build this package from the local machine work as expected.

If I try to run 

\\<hostname>\BoxShare\Boxstarter MyTestPackage 

From a remote machine it fails when it gets to the chocolately install complaining that it cannot find my package. Is this because the localrepo config isn't being shared with the remote machine ?

Can I tell the remote running install of BoxStarter to look somewhere else for it's local repo ?

**Comment by johnkattenhorn** [comment]
Note to self - Don't be a easy a**e and read the source code. Boxstarter.bat is a wrapper around Invoke-ChocolateyBoxstarter which takes a -LocalRepo parameter.

So from a remote machine a could run 
    \\<machine-name>\BoxShare\Boxstarter MyTestPackage -LocalRepo \\<machine-name>\\BoxShare\BuildPackages

And it ran fine.

**Comment by mwrock** [comment]
My apologies for not responding sooner. You are correct about the wrapper ant that will certainly work. You can also permanently change the local repo location using:

```
Set-BoxstarterConfig -LocalRepo <new path>
```

**Comment by johnkattenhorn** [comment]
Hey @mwrock, dude you're too busy already to worry about my trivia! 

Should that setting be honoured by the remote machine then ? i.e. If I run Set-BoxstarterConfig -LocalRepo C:\BuildPackages on the host machine and then on a guest run \\<machinename>\boxshare\boxstarter MyTestPackage should the host machine look for the package in C:\BuildPackage.

Or should I be running Set-BoxstarterConfig -LocalRepo on the guest first referencing the shared location for the packages on the host ?

**Comment by mwrock** [comment]
Ahh. No. Set-BoxstarterConfig only affects the machine from which it has been run.
