### ISSUE TITLE
Typo boxstarter.org

### ISSUE THREAD

**Issue by DavidDeSloovere** [mwrock/boxstarter#52]
Hi Matt, there's a typo in this piece of text:

Repeatable, reboot resilient windows environment installations made easy using Chocolatey packages. When its time to repave either bare metal or virtualized instances, locally or on a remote machine, Boxstarter can automate both trivial and highly complex installations. Compatible with all Windows versions from Windows 7/2008 R2 forward.

Found it? No? The typo is... "its", which should be "it's"

**Comment by gep13** [comment]
Pull Request submitted to correct typo

**Comment by DavidDeSloovere** [comment]
Oops, didn't realize that was in github too. Otherwise I would just have fixed it.

**Comment by gep13** [comment]
> Oops, didn't realize that was in github too. Otherwise I would just have fixed it.

:smile_cat: not a problem at all, it only took a couple minutes to fix up.  Yeah, @mwrock pretty much as everything associated with boxstarter in this one repository.

**Comment by mwrock** [comment]
Thanks guys for noticing and fixing!! :)
