### ISSUE TITLE
Boxstarter fails when chocolatey-community-validation.Extension is installed

### ISSUE THREAD

**Issue by flcdrg** [mwrock/boxstarter#560]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Boxstarter fails to create temporary package and fails with the following error:

CPMR0009: A project URL for the software is either missing or empty
CPMR0032: The description has a length of 19 characters. ....

### What is Expected?

Temporary package should not fail validations

### How Did You Get This To Happen?

Boxstarter script includes installing the chocolatey-community-validation.Extension package

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
chocolatey-community-validation.Extension
```

### Output Log

```bash
-
```

**Comment by mwallner** [comment]
Adding
```
<projectUrl>https://boxstarter.org</projectUrl>
```
and modifying 
```
<description>
```

in `New-BoxstarterPackage` should do the trick. => PR should follow soon, I'd like to get 3.1 wrapped up asap.
