### ISSUE TITLE
Merge individual function scripts into a PowerShell module file

### ISSUE THREAD

**Issue by pauby** [mwrock/boxstarter#563]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

The PowerShell functions are all in their individual scripts (`.ps1`) and are dot sourced into the PowerShell module file (`.psm1`). This is not recommended practice and means the scripts are individually signed.

### Describe The Solution. Why is it needed?

It is recommended best practice to merge these individual script files into one PowerShell module file at build time, and ship that.

### Additional Context

N/A

### Related Issues

N/A

**Comment by mwallner** [comment]
I'd propose to use [Sampler](https://github.com/gaelcolas/Sampler) for this

**Comment by pauby** [comment]
Can a simple, few lines of code, appending the functions into a file not be a simpler, and less reliant on external 3rd parties, option?

**Comment by mwallner** [comment]
Most likely, is there an oss code sample you could point me to as a reference?

**Comment by pauby** [comment]
There is some code over in [PowerShellBuild that would help](https://github.com/psake/PowerShellBuild/blob/main/PowerShellBuild/Public/Build-PSBuildModule.ps1#L101-L140).
