### ISSUE TITLE
Boxstarter.zip for remote setup doesn't contain compiled modules

### ISSUE THREAD

**Issue by mwallner** [mwrock/boxstarter#579]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [ ] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

When building/ using the latest source from "develop", remote installations fail due to Boxstarter.zip missing the compiled modules.

### What is Expected?

The modules in the remote-installation zip should be the same as in the nupkgs.

### How Did You Get This To Happen?

use the existing buildscripts in order to create the nupkg/boxstarter.zip files.

```
./build Package
```

### Additional Context

introduced with #563

**Comment by pauby** [comment]
@mwallner can you complete the template sections fully?

**Comment by mwallner** [comment]
> @mwallner can you complete the template sections fully?

sorry, not sure how to do this with an already-created issue...

tbh, I was unsure on how to proceed with this, since this is a fix/issue for something that's not yet included in a release. (#565 has been merged but is incomplete without this addition/fix)

**Comment by pauby** [comment]
> sorry, not sure how to do this with an already-created issue...

You just need to edit the description, put back all the sections removed and add in the information requested. The template should not be edited to remove sections.

> tbh, I was unsure on how to proceed with this,

This should just be completed as a normal issue.
