### ISSUE TITLE
Parallel package installs to multiple targets at same time

### ISSUE THREAD

**Issue by talberthoule** [mwrock/boxstarter#58]
I adapted the code so we can define the installation of multiple packages to many computers by either manually typing them in, importing them with a text file, AD group, or OU.  This works great, for the most part, but I am seeing a problem with consistently installing all packages on every computer.  

There is a simple function within my powershell script, called install:

    $install = {
	#import variables
	param( $c1, $package, $cred, $rboot )
	    foreach ($p in $package){
		    if($rboot -eq "y"){
			install-boxstarterpackage -computername $c1 -packagename $p -credential $cred -disablereboots
		    }
		    else{
			install-boxstarterpackage -computername $c1 -packagename $p -credential $cred
		    }
	    }
    }

...which is called by: 

    foreach ($c1 in $computer1){
	    start-job -scriptblock $install -argumentlist $c1,$package,$cred,$rboot -name "$c1 -$package"
	    #get-job | wait-job 
    }

If I do not comment out the *get-job | wait-job*, I am seeing the following error on at least one of the package installations for at least one of the computers I am installing to, which causes a package to not install:

**The process cannot access the file 'C:\Users\thoule\AppData\Local\Boxstarter\boxstarter.log' because it is used by another process.**
* **CategoryInfo               : OpenError: (:) [Out-File], IOException**
* **FullyQualifiedErrorID  : FileOpenFailure,Microsoft.Powershell.Commands.OutFileCommand**
* **PSComputerName      : localhost**

If I uncomment the *get-job | wait-job* code so it processes each computer one at a time, everything works, but this would take forever if I were to try and install packages to say 100's or 1000's of computers.  

Anyone have any ideas how I can get around this problem?

**Comment by mwrock** [comment]
Yeah this is from your two parallel runs trying to write to the same file at the same time. When performing a remote install, all remote activity is written to the log on the remote machine which obviously will not cause contention. However, some logging is done locally regarding connection attempts and reboots.

You may be able to resolve this by staggering the runs by just a few seconds so that the initial connection logging will not occur at the same time.

**Comment by talberthoule** [comment]
Thank you, Matt.  I told it to pause for two seconds and that took care of it.
