### ISSUE TITLE
Upgrade choco-theme to the latest version

### ISSUE THREAD

**Issue by alexaveldanez** [mwrock/boxstarter#584]
### Checklist

- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

boxstarter.org needs to be upgraded to latest version of choco-theme.

### Describe The Solution. Why is it needed?

This is needed so that boxstarter.org is updated to the latest version of choco-theme.

**Comment by st3phhays** [comment]
Closed due to being created in the wrong repository by mistake.
