### ISSUE TITLE
Installing more than once with web launcher

### ISSUE THREAD

**Issue by jnus** [mwrock/boxstarter#60]
Hi

It it possible to run a bs script more than once with the boxstarter web launch application? It seems to build the temp_BoxstarterPackage version 1.0.0 and once you've installed one script with the web launcher, you can't install another, without first removing temp_BoxstarterPackage v1.0.0 manually. Any workarounds?

**Comment by Manuel-S** [comment]
I noticed the name of the package, before. Maybe name the package after the url from which it is installed, optionally provide a url parameter. Example:

```
http://boxstarter.org/package/url?http://www.my-domain.com/example-boxscript.txt
```
=> PackageName = example-boxscript

```
http://boxstarter.org/package/my-machine/url?http://www.my-domain.com/example-boxscript.txt
```

=> PackageName = my-machine

**Comment by mwrock** [comment]
"In Theory" this should be possible. Pasting my response to a related issue here:

When using a gist, boxstarter generates the `temp_BoxstarterPackage`. Boxstarter will always remove the package from the chocolatey cache before installing to avoid this situation. One possibility that comes to mind is that the host is somehow in a weird transitory state between chocolatey versions where chocolatey moved its cache from `c:\chocolatey` to `c:\ProgramData\Chocolatey` and boxstarter is removing from one location and chocolatey is looking in another. You might try looking to see if you have two chocolatey installations and also checking if the `ChocolateyInstall` environment variable is pointing to the correct location.

**Comment by jnus** [comment]
Manuel-S: Settings the meta data seems to work, although the in the log I still get the temp_BoxstarterPackage 1.0.0. 

Solution #1, with url parameters, I can't get to work. The web launch prefix url simply fails. Should this be possible?

mwrock: I'm pretty sure this is happening with freshly installed machines, where chocolatey only has been installed once, by the web launcher  - I'll confirm and post back the result.

**Comment by mwrock** [comment]
And just to clarify a repro, say you have this gist based url: http://boxstarter.org/package/nr/url?https://gist.githubusercontent.com/mwrock/d047eb650f6bb029ddd3/raw/50873661b36af7f15ad265b60be1518b07d45abb/gistfile1.txt

You run it once and boxstarter installs. Then you take that same url and run it again and are told that the package has already been installed.

Is that correct? Can you share your url?

**Comment by jnus** [comment]
Reproduced the error today with the following gist: 
https://gist.githubusercontent.com/jnus/c70e020d050dfbfd2780/raw/0d0219f22468678e9b9bc36de3c7879703c4b8d4/gistfile1.txt

I've run it on a Windows Server 2008 r2, with not prior installations. Result:
![capture](https://cloud.githubusercontent.com/assets/2075403/6212774/0b7455aa-b5e9-11e4-8f84-3867e851e5a9.PNG)

Running it once more, results in the following output:
![capture1](https://cloud.githubusercontent.com/assets/2075403/6212777/17ccf514-b5e9-11e4-87e5-935d0f699a1c.PNG)

**Comment by mwrock** [comment]
thanks! this is helpful. will fire up a 2k8r2 vm tonight.

**Comment by taebox** [comment]
This was a really frustrating issue. I just ended up wiping out the Chocolatey dir.

**Comment by mwrock** [comment]
My apologies this took so long. Just got back from vacation. I'm hoping to release this fix tomorrow.
