### ISSUE TITLE
Detect Firefox ClickOnce support

### ISSUE THREAD

**Issue by Redsandro** [mwrock/boxstarter#61]
This is not directly boxstarter related but there is probably the most related knowledge here.

The [Microsoft .NET Framework Assistant](https://addons.mozilla.org/nl/firefox/addon/microsoft-net-framework-assist) Firefox extension does not add `mimeType` to the `navigator` object, and there is no `.NET` or `CLR` in the `userAgent` string. Is there any way to detect the presence of this extension in Firefox?

I would like to be able to switch between the Boxstarter link or the extension page based on whether or not it is already installed.

https://addons.mozilla.org/nl/firefox/addon/microsoft-net-framework-assist/reviews/679628/

**Comment by mwrock** [comment]
Just doing some cursory googling I've found a few leads on detecting specific Firefox extensions. Here's one:

http://www.codeproject.com/Articles/28241/Detecting-a-Firefox-Extension-Using-JavaScript

Hope that helps.

**Comment by Redsandro** [comment]
Thanks for googling. However, 7 years have past since that article was written and those internal urls are no longer retrievable for content that is not explicitly manifest'ed as public. I've probably tried most of the stuff you find in the first few result pages. You can no longer detect .NET presence, detect the mimeType, verify content from `chrome://` or the likes, or use `Application.getExtensions()` for this.

Could be that someone here was actively using such ClickOnce trickery in Firefox and knows how to deal with this. As for Google, pretty much everything is outdated.

[I wish Microsoft would answer the question or update their plugin](https://twitter.com/Redsandro/status/570349283758571520). Please retweet. :smile:

**Comment by Redsandro** [comment]
Maybe this helps. https://github.com/Microsoft/dotnet/issues/185

**Comment by Redsandro** [comment]
> Maybe this helps

Turns out it did. Please reply to the thread. See https://github.com/mwrock/boxstarter/issues/251
