### ISSUE TITLE
Ability to change other Windows Update options

### ISSUE THREAD

**Issue by rpavlik** [mwrock/boxstarter#62]
Apologies if I missed this in the docs - but it would be nice to be able to at least turn on the "Check for updates to other microsoft products" option in a Boxstarter script. For reference, I'm looking at the settings page of the Windows Update desktop control panel of a Server 2012 R2 machine.

**Comment by gep13** [comment]
Just wanted to check, I think this `Enable-MicrosoftUpdate` as documented here:

http://boxstarter.org/WinConfig

Is what you are after.

I know that this works on Windows 7 and 8, as when I added in this option that I what I tested on, but I can't say that I have run this on a Windows 2012 machine, although it should be the same.

Hopefully this will work for you.

**Comment by rpavlik** [comment]
Ah, yep, that will do it. Sorry I missed that. Thanks!

**Comment by gep13** [comment]
Not a problem, happy to help :+1:
