### ISSUE TITLE
Cannot install boxstarter via choco with choco version 0.9.9.2

### ISSUE THREAD

**Issue by dfranciscus** [mwrock/boxstarter#65]
Is this a known issue with the latest version of chocolatey? I have tried it on a windows 7 machine and a Server 2012 R2. Same result.

boxstarter.chocolatey v2.4.183 (forced)
 WARNING: Write-ChocolateyFailure is deprecated. If you are the package maintainer, please use 'throw $_.Exception'
 instead.
 The term 'chocolateyInstaller\Write-Host' is not recognized as the name of a cmdlet, function, script file, or
 operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
 again.
 At C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1:24 char:3
 +   throw "$failureMessage"
 +   ~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (The term 'choco... and try again.:String) [], RuntimeException
     + FullyQualifiedErrorId : The term 'chocolateyInstaller\Write-Host' is not recognized as the name of a cmdlet, fun
    ction, script file, or operable program. Check the spelling of the name, or if a path was included, verify that th
   e path is correct and try again.
boxstarter.chocolatey install not successful.
Error while running 'C:\ProgramData\chocolatey\lib\boxstarter.chocolatey\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by mwrock** [comment]
Yup. The best way to install boxstarter right now is to use the web installer from IE: Http://boxstarter.org/package/nr/boxstarter

**Comment by dfranciscus** [comment]
Thanks. Is there any ETA on when this may be fixed? Your solution is awesome but I need to push it to many remote machines.

**Comment by mwrock** [comment]
Hope to release a fix tonight. This should only affect local installs of boxstarter via chocolatey or the installer downloaded in the boxstarter zip. Once installed locally, romote installs "should" work.

Thanks!

**Comment by mwrock** [comment]
The fix for this has been released in 2.4.188. Let me know if you have further issues. Thanks!
