### ISSUE TITLE
Ability to pass variables to ChocolateyInstall.ps1 from Install-BoxstarterPackage

### ISSUE THREAD

**Issue by robertward** [mwrock/boxstarter#66]
I'm trying to create a script where I can rename computers and the ability to passthru a custom variable (in this case a desired hostname) would be great.

So the ChocolateyInstall.ps1 script could be:
if ($env:COMPUTERNAME -ne "$outsidevariable")
{
    Write-Host "Renaming computer"
    Rename-Computer -NewName "$outsidevariable" -Force
    Invoke-Reboot
}

**Comment by mwrock** [comment]
Currently one is fairly limited in what can actually be passed through to chocolatey from the initial call. I think we should be able to support all the arguments that cinst provides which would account for this scenario.

In the meantime you may be able to accomplish this by placing these values in a file that the package can read from, but I'd admit that's less than ideal.

**Comment by mwrock** [comment]
This will be fixed in v2.6 which will embed the latest chocolatey and you can pass in variables using the standard flags of `choco install`.

**Comment by dragon788** [comment]
I noticed somewhere while reading today that you mentioned passing the `-y` to the `choco install` isn't currently supported/required, so it should just be `choco install packagename -params 'param1;param2'` or `choco install packagename --ignore-checksums`.
