### ISSUE TITLE
Feature Request: Support -Force on Invoke-Reboot

### ISSUE THREAD

**Issue by nbarnwell** [mwrock/boxstarter#70]
This is so a reboot can happen even if RebootOK is false. I know it sounds crazy, but I have a weird situation where I need the auto-reboot stuff turned off (a weird file is in the pending file renames registry entry that I can't get rid of) but after installing Visual Studio, for example, I know I want to force a reboot.

I tried setting $Boxstarter.RebootOK = $true before calling Invoke-Reboot but it remembered that setting when writing the reboot file and back into my reboot loop I went. :)

**Comment by mwrock** [comment]
Try adding `$Boxstarter.RebootOK = $false` as the first line of your script. Not sure that will work but hopefully it will reset the reboot shutoff.

**Comment by mwrock** [comment]
just curious if this worked?

**Comment by nbarnwell** [comment]
Unfortunately not as the reboot was happening before my script was invoked.
The problem in the end was a weird IGT.exe in the startup start menu
folder, that was referenced in the pending renames registry key. I tried
with a Win7 and Win8 VM with the same script with no issues, so I'm back to
using automated reboot checks. The problem must be some weird
incompatibility with Parallels and the Win10 preview of Windows I was
using. I was never sure it was Boxstarter's fault, tbh, but Invoke-Reboot
-force would've helped me work around it (I'm aware I could've forked that
script into my package and called a modified version if it came to it).

Thanks for checking back. Very pleased with Boxstarter now I have this
issue worked out.


Neil Barnwell.
*Mobile:* 07900 221457
*Twitter:* @neilbarnwell
*e-mail:* mailbox@neilbarnwell.co.uk
*web:* http://www.neilbarnwell.co.uk

**Comment by gep13** [comment]
@nbarnwell you might want to edit the above, as it include you mobile phone number :-)

**Comment by nbarnwell** [comment]
Thanks. Hooray for using Google Mail to reply to such things, eh?

**Comment by mwrock** [comment]
Ok. I'll close this. One reason why I am hesitant to add -force is package consumers need insurance that disabling reboots works and someone could easily and accidentally add -force when it is not needed and invoke a reboot.

That said I certainly understand your dilemma.
