### ISSUE TITLE
Add "Checkpoints" like PowerShell Workflows

### ISSUE THREAD

**Issue by DarwinCSIWindowscom** [mwrock/boxstarter#72]
I have tacked on my own by creating and looking for files - but it would be handy to have it natively built in.

When a boxstarter script restarts, it starts right after the last completed checkpoint.  Helps speed things up on very long workflows.

**Comment by mwrock** [comment]
Hmm. I have thought about this previously. I'd really prefer to keep the scripts "idempotent". I think this is simpler and less error prone in the end. It also sticks to the "pattern" most other automation tools suport.

**Comment by mwrock** [comment]
But thanks for the suggestion and please feel free to send any more our way!
