### ISSUE TITLE
Support 'choco pin'

### ISSUE THREAD

**Issue by mjiderhamn** [mwrock/boxstarter#73]
It would be great if BoxStarter besides the `cinst`/`choco install` command also supported the [`choco pin` command](https://github.com/chocolatey/choco/wiki/CommandsPin), so that package versions can be pinned as they are installed on a new box.

Currenty, `choco pin add -n=mysql` in your BoxStarter script tries to `choco install` "add" and "-n=mysql" (but AFAI can tell not "pin")...

**Comment by mwrock** [comment]
Currently, even if you have the new choco installed, boxstarter uses the v0.9.8.33 powershell module. The new choco.exe fundamentally changes how boxstarter needs to interact with chocolatey and its a top priority to get boxstarter to be compatible with that. When that does happen, I expect `choco pin` to work.
