### ISSUE TITLE
Check-Chocolatey failing when attempting to install .NET 4.5

### ISSUE THREAD

**Issue by joe-niland** [mwrock/boxstarter#75]
I am attempting to run a BoxStarter package on a VM which does not have Chocolatey or BoxStarter installed. BoxStarter is correctly attempting to install Chocolatey and its dependencies, however I am running into an issue which seems to be related to the `$env:Temp` path.

See below for an example of what I am seeing.

It seems that when downloading .NET 4.5, $env:Temp resolves to C:\Users\Administrator\AppData\Local\Temp, but when attempting to invoke net45.exe via a Scheduled Task, it can't seem to find the file.

I've verified the installer has been downloaded to: C:\Users\Administrator\AppData\Local\Temp\net45.exe

And when I decode the Scheduled Task command from the temporary BoxStarterTask.ps1 file, it is: `$ProgressPreference='SilentlyContinue';Start-Process "C:\Users\ADMINI~1\AppData\Local\Temp\net45.exe" -verb runas -wait -argumentList "/quiet /norestart /log C:\Users\ADMINI~1\AppData\Local\Temp\net45.log"`

At first I thought it was due to the RDP Temp Directory settings (see: http://stackoverflow.com/a/6521387/366965) but I disabled this behaviour and it is still occurring.

When I have some more time, I'll do some more debugging, but any ideas?

Thanks!

```
C:\vagrant\win2008r2> Install-BoxstarterPackage -PackageName Install-SSLBestPractices -ComputerName win2008r2x64 -credential $cred
Boxstarter Version 2.4.188
(c) 2015 Matt Wrock. http://boxstarter.org

Boxstarter: Configuring local PowerShell Remoting settings...
Boxstarter: Configuring CredSSP settings...
Boxstarter: Testing remoting access on win2008r2x64...
Boxstarter: Remoting is accessible on win2008r2x64
Boxstarter: Copying Boxstarter Modules and LocalRepo packages at C:\Users\user1\AppData\Roaming\Boxstarter to R:\temp\ on win2008r2x64...
[WIN2008R2X64]Boxstarter: Downloading .net 4.5...
[WIN2008R2X64]Boxstarter: Installing .net 4.5...
ERROR: The system cannot find the file specified.
    + CategoryInfo          : NotSpecified: (ERROR: The syst...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : win2008r2x64

NotSpecified: (:) [], RemoteException
```

**[... tries the above download & install a few more times ...]**

```
Install-BoxstarterPackageOnComputer : Unable to run scheduled task. Message from task was
At C:\Users\user1\AppData\Roaming\Boxstarter\Boxstarter.Chocolatey\Install-BoxstarterPackage.ps1:359 char:21
+                     Install-BoxstarterPackageOnComputer $_ $sessionArgs $Package ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-BoxstarterPackageOnComputer



Errors       : {Unable to run scheduled task. Message from task was , NotSpecified: (:) [], RemoteException, ERROR: The system cannot find
               the file specified., NotSpecified: (:) [], RemoteException...}
ComputerName : win2008r2x64
Completed    : False
FinishTime   : 19/03/2015 4:20:08 PM
StartTime    : 19/03/2015 4:18:31 PM

Boxstarter: Rolling back remoting settings changed by Boxstarter...
```

**Comment by mwrock** [comment]
Thanks for reporting this. I have a repro and hope to get a fix out soon.

**Comment by mwrock** [comment]
Just pushed 2.4.194 to fix bug introduced in the chocolatey 0.9.9 compat work. Thanks again for reporting this.

**Comment by joe-niland** [comment]
No worries, Matt. Thanks for the quick response and a great project!

**Comment by joe-niland** [comment]
I've now had time to test this and it seems that I'm still seeing the same issue: "The system cannot find the file specified.", etc..

The error seems to be something to do with the scheduled task removal.
I found that if I stop the removal of the "Boxstarter Task" scheduled task (by commenting out [this line](https://github.com/mwrock/boxstarter/blob/master/BoxStarter.Common/Remove-BoxstarterTask.ps1#L17)) then the .NET 4.5 installation will proceed, along with the remote package installation

I haven't yet been able to figure out why the above causes the .NET installation to work, but I thought I'd mention it here in case you can point me in the right direction.

**Comment by mwrock** [comment]
I have a fix lined up for this and hope to release tomorrow. Thanks!

**Comment by joe-niland** [comment]
Thank you! Will test when released.

**Comment by mwrock** [comment]
ok give this a try when you have a chance 2.4.205 just released.

**Comment by joe-niland** [comment]
All good here now. I was able to install a package remotely on a fresh win2008 vagrant box (which does not have .NET 4.5, BoxStarter or Chocolatey installed.) Thanks Matt!
