### ISSUE TITLE
installing on remote

### ISSUE THREAD

**Issue by larsbarst** [mwrock/boxstarter#76]
im using:
$cred=Get-Credential name/username
install-boxstarterpackage -computername name -packagename package -credential 

itas starting an nuget process but not adding the program
im using flash msi as installer.

**Comment by larsbarst** [comment]
try {
 
    Write-ChocolateySuccess 'Test2'
} catch {
  Write-ChocolateyFailure 'Test2' $($_.Exception.Message)
  throw
}
is my chocoinstall.ps1

**Comment by mwrock** [comment]
ok. This makes more sense now. 

This will simply output "Test2" and end. I'd check out the chocolatey.org site for guidance on writing packages that install MSIs. But here is a simple example:

```
if(Test-Path "$env:ProgramFiles\Microsoft SDKs\Azure\.NET SDK\v2.5") {
    Write-Host "Windows Azure Libraries for .net v2.5 is already installed."
    return
}
Install-ChocolateyPackage 'WindowsAzureLibsForNet' 'msi' '/quiet /norestart' 'http://download.microsoft.com/download/9/F/7/9F7D3299-9AE1-40BE-B24F-C0E9EB0BE61E/MicrosoftAzureLibsForNet-x86.msi' 'http://download.microsoft.com/download/9/F/7/9F7D3299-9AE1-40BE-B24F-C0E9EB0BE61E/MicrosoftAzureLibsForNet-x64.msi'
```

Chocolatey provides several helpers like `Install-ChocolateyPackage` above. Check it out for a full list of them and docs.

**Comment by larsbarst** [comment]
there is not just create package then put the installer in it and it will use default arguments?
how can i use the install-chocolateypackage then to use remotely

**Comment by mwrock** [comment]
You want write the chocolatey package as if it were local. Boxstarter will transfer the script to the box and then it runs locally.

Unless you are the software author, you dont want to include the actual installer in the package, instead you you'd download it from the internet.
