### ISSUE TITLE
Support a Per-Machine Install in Chocolatey Package for Boxstarter

### ISSUE THREAD

**Issue by DarwinCSIWindowscom** [mwrock/boxstarter#77]
I have some Ops who have to change profiles during a build process.

Would be nice if boxstarter could be installed to ProgramData where it could be accessed by all profiles and referenced in a consistent manner when calling it in other scripts.

ProgramData would not require admin rights.

Thanks,
D.

**Comment by mwrock** [comment]
Yup. This was also mentioned in #32 but this more succinctly captures the issue so I'm gonna track it here. Thanks!

**Comment by samjetski** [comment]
Installing to ProgramData would be more consistent with chocolatey's approach, and would also be more friendly for use in scheduled tasks, etc.

It's a bit odd installing to a user's AppData because chocolatey tracks package installations system-wide (in ProgramData) so if another user wanted boxstarter they would need to "reinstall". Starts getting weird...

**Comment by samjetski** [comment]
Would probably be as simple as changing [setup.ps1](boxstarter/BuildScripts/setup.ps1) from:
```
$boxstarterPath=Join-Path $env:AppData Boxstarter
```
to
```
$boxstarterPath=Join-Path $env:ProgramData Boxstarter
```
and from:
```
$value = [Environment]::GetEnvironmentVariable($variableName, 'User')
...
[Environment]::SetEnvironmentVariable($variableName, $values, 'User')
```
to
```
$value = [Environment]::GetEnvironmentVariable($variableName, 'Machine')
...
[Environment]::SetEnvironmentVariable($variableName, $values, 'Machine')
```

If you think the above changes are sufficient then I'll submit a pull request.

However, this is potentially a breaking change. Specifically, existing installations with packages in `$boxstarterPath\BuildPackages` would need these to be moved when upgrading. Ought this be performed by the upgrade, or the user's responsibility?

The installation location could alternatively be controlled through `$installArgs`, but I think the default ought to change to `ProgramData` regardless for system-wide consistency.

**Comment by mwrock** [comment]
A PR would be great @samjetski !

**Comment by KZeronimo** [comment]
I just ran into this as well - I think the suggested changes in the proposed PR make sense - this following should be vetted

> However, this is potentially a breaking change. Specifically, existing installations with packages in $boxstarterPath\BuildPackages would need these to be moved when upgrading. Ought this be performed by the upgrade, or the user's responsibility?

What are the thoughts on the best path forward

**Comment by KZeronimo** [comment]
I should have looked #221!

Does this need anymore help - looks like you wanted to strip the user install completely and only go with machine

**Comment by mwrock** [comment]
I'm just waiting for recent chocolatey updated to stabilize before pulling in #221.

**Comment by brettjacobson** [comment]
Is chocolatey stable enough for this change yet?

**Comment by lordmuffin** [comment]
@mwrock As @brettjacobson said above, where are we at with this?  I noticed this has issues running in any scenario where the boot strapper is running as system(most cloud deployments).

**Comment by mwrock** [comment]
just merged that PR along with changes to docs. Will go out in next release soon.
