### ISSUE TITLE
Windows 7 login fails

### ISSUE THREAD

**Issue by ianchanning** [mwrock/boxstarter#78]
I just did a re-install of Windows 7 Professional 64-bit. Then after the installation and having created my account for the first time but before doing any restarts I followed your [Web Launcher guide](https://www.boxstarter.org/WebLauncher) and ran the following URL in IE8 (http://boxstarter.org/package/url?https://gist.githubusercontent.com/ianchanning/1086c8834355d3c5c8ba/raw/0b6f7a66730fc0d7dd1376ac29060507eae6f64d/blackjack-boxstarter.txt)

 I left out the 'nr' part of the URL to ensure that it would do the automatic rebooting.

One of the first parts of the process - I think after BoxStarter is installed is to ask for the password for the auto reboots. I filled this in and it authenticated fine according to the BoxStarter logs on the screen.

However any logins as part of the reboot process failed. Each time it would get to the login screen and fail with a 'The user name or password is incorrect'. The screen I'm shown is something like the below (its an image from the internet). 

![logon failure screenshot](https://cloud.githubusercontent.com/assets/233318/6771884/93bbbe3e-d0ed-11e4-8fb7-57a87fa77f43.jpg)

If I click 'Ok' I'm taken to the login page where I can only enter my password. Again see the below image for what I mean (again not my actual screenshot). 

![aa00120](https://cloud.githubusercontent.com/assets/233318/6771887/bef8605c-d0ed-11e4-8ac3-22e90a0751c3.png)

All I can think of that might be causing this problem is that you can't fill in the username. Apart from the reboots all the installations went smoothly.

**Comment by ianchanning** [comment]
Here is the [boxstarter.log](https://gist.github.com/ianchanning/ad37d4552b32990c65a0). It indicates that it stored my password correctly but it appears that it didn't. Once boxstarter was complete it continued to attempt to autologon every time with a failed password. I fixed it by running sysinternals autologon.exe and altering the password.

```
[2015-03-22T13:28:10.9249920+01:00:::PID 2828] Boxstarter may need to reboot your system. 
Please provide your password so that Boxstarter may automatically log you on. 
Your password will be securely stored and encrypted.
[2015-03-22T13:28:47.8658569+01:00:::PID 2828] Boxstarter: Successfully authenticated password.
[2015-03-22T13:28:47.9126569+01:00:::PID 2828] Boxstarter: NoPassword is set to False and RebootOk is set to True and the NoPassword parameter passed was False
```

**Comment by mwrock** [comment]
Sorry for not responding earlier. I've definitely installed countless times on win7 but there are always interesting edge cases. However we test less and less on win7 so could be a regression.

 My guess is that this is more a failure of the user name than password. Box starter captures the identity of the current user and uses that user name. I've seen issues in the past where a user was running under local system or a different domain and that led to issues.

The log file should include the user name that it used when attempting to authenticate. I'll try to make a point of testing a local install with win7 soon to verify the normal path is working and see if this reproduces.

**Comment by mwrock** [comment]
I just tested on windows 7. I didn't run into a problem with the autologon but I certainly realize there are a lot of edge cases and environmental issues that can be at play here. If you look at the log file in %localappdata%\boxstarter\boxstarter.log, you should see some lines resembling the following:

```
[2015-03-30T21:49:29.0832500-07:00:::PID 1036] Boxstarter: Enabling Automatic Updates from Windows Update
[2015-03-30T21:49:29.1301250-07:00:::PID 1036] Boxstarter: UAC Enabled. Disabling...
[2015-03-30T21:49:29.1457500-07:00:::PID 1036] Boxstarter: Disabling UAC
[2015-03-30T21:49:29.2082500-07:00:::PID 1036] Boxstarter: Securely Storing win7\mwrock credentials for automatic logon
[2015-03-30T21:49:31.4270000-07:00:::PID 1036] Boxstarter: Logon Set
[2015-03-30T21:49:31.4270000-07:00:::PID 1036] Boxstarter: Restart Required. Restarting now...
[2015-03-30T21:50:58.5785000-07:00:::PID 1844] Boxstarter Version 2.4.196
[2015-03-30T21:50:58.5941250-07:00:::PID 1844] (c) 2015 Matt Wrock. http://boxstarter.org
```

If you look for a line containing the string "Securely Storing", you will find the username that boxstarter will use for the autologon. It would be interesting to see if this jives with what you expect it should be.

**Comment by ianchanning** [comment]
Cheers for looking into this. I'd put the log into a [private gist](https://gist.github.com/ianchanning/ad37d4552b32990c65a0), it has the following lines in it:

```
[2015-03-22T13:28:48.4586579+01:00:::PID 2828] Boxstarter: UAC Enabled. Disabling...
[2015-03-22T13:28:48.4742579+01:00:::PID 2828] Boxstarter: Disabling UAC
[2015-03-22T13:28:48.4898580+01:00:::PID 2828] Boxstarter: Securely Storing BLACKJACK\Ian credentials for automatic logon
[2015-03-22T13:28:49.5818599+01:00:::PID 2828] Boxstarter: Logon Set 
```

The BLACKJACK\Ian is correct.

I had created another user but the auto logon was definitely set to attempt to logon to my account. i.e. everytime the computer is turned on it would automatically come up with the failed logon screen of my username 'Ian'. This is after the boxstarter process had finished.

I thought perhaps it might have set a blank password by mistake - but I couldn't find where in the registry it stores the encrypted password, the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon` had the `DefaultUserName` key set to 'Ian'. 

The only other thing that I noted was that the default domain was blank for the autologon. But I doubt that signifies much.

**Comment by mwrock** [comment]
one thing that would be helpful to troubleshoot this is to directly call boxstarter's function that sets the credentials and then reboot and see if the autologon works or not.

Here is how you would do that:
1. Save the contents of https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Set-SecureAutoLogon.ps1 to a file. For the sake of these instructions we will assume you are saving to `c:\dev\Set-SecureAutoLogon.ps1`
2. Open up a powershell console as administrator
3. Load the above file by entering `. c:\dev\Set-SecureAutoLogon.ps1`
4. Call the function using:
```
Set-SecureAutoLogon -username ian -domain BLACKJACK -password $(ConvertTo-SecureString "YOUR_PASSWORD" -AsPlainText -Force)
```
5. Restart the computer

If the auto logon fails or succeeds this helps to isolate the problem.

**Comment by shamp00** [comment]
I'm having the same problem with two different machines (Windows 8.0 and Windows 8.1). I tried your troubleshooting instructions on both and sure enough the login fails: 

> The username or password is incorrect. Try again.

This used to work fine on both machines, so I tried older versions of `Set-SecureAutoLogon.ps1` from the history but they all still fail. Maybe it's the result of a Windows Update. Is there anything else I can try to help isolate the problem?

**Comment by mwrock** [comment]
The only thing I can think of is to try using the sysinternals autologon tool https://technet.microsoft.com/en-us/library/bb963905.aspx. This should in theory do the same thing as boxstarter's autologon but would at least validate that even a completely non boxstarter code path fails.

**Comment by ianchanning** [comment]
Sorry for the slow response. I've tried the `Set-SecureAutoLogon.ps1` via the administrator powershell and it set the auto-logon correctly.

**Comment by shamp00** [comment]
Sysinternals autologon works fine. And after I ran it again to disable auto logon, it seems to have fixed BoxStarter's autologon which is now working fine.

**Comment by mwrock** [comment]
I finally stumbled on a repro for this bug. It started happening on a couple of my VMs. It happens if you have a `DefaultPassword` registry property even if it is empty which it probably is. Its likely that you may have successfully run boxstarter and then run into this issue on all subsequent runs. When boxstarter restores the `winlogon` registry properties when it is done, it adds an empty `DefaultPassword` property. This causes autologon to fail and NOT read from the correct source - the LSA encrypted secrets instead of the plain text registry properties.

This is fixed and will be released tonight or tommorow.

**Comment by shamp00** [comment]
Great news! Nice find. It makes sense - I usually run BoxStarter to update my main development machine, rather than creating a new VM from scratch each time. So once it was broken it would remain broken. I did notice that empty <code>DefaultPassword</code> registry key but didn't know what conclusions to draw from it. Thanks for the update.
