### ISSUE TITLE
Import-Module fails for module that exists

### ISSUE THREAD

**Issue by SurajGupta** [mwrock/boxstarter#82]
I'm calling `Import-Module NetSecurity` in my Boxstarter package.  I get the following error:

    Message        : The specified module 'NetSecurity' was not loaded because no v
                     alid module file was found in any module directory.
    FileName       : 
    FusionLog      : 
    Data           : {}
    InnerException : 
    TargetSite     : 
    StackTrace     : 
    HelpLink       : 
    Source         : 
    HResult        : -2147024894

However, when I fire-up PowerShell and type the same command on the box, it works just fine.  Oddly, the BoxStarter package will execute a cmdlet within NetSecurity just fine, even though the Import-Module is failing.

So I guess it's not strictly a problem because I can just remove the Import-Module line.  Given the prior bug I logged (https://github.com/mwrock/boxstarter/issues/81), I'd really like to understand the differences between PowerShell execution in the normal case, and within the context of a BoxStarter package because it seems subtly different.

**Comment by mwrock** [comment]
That is odd. What os are you installing on? Is it possible to share your package or script?

**Comment by SurajGupta** [comment]
Hi Matt,  Here's how to repro...  I'm using a clean install of Windows 8.1 in a Hyper-V VM.  I could spend some time shrinking the package down further if helpful?

**package contents**

    function Test()
    {
    	cinst ruby -y
        cinst rubygems -y
        cinst ruby2.devkit -y
        cinst python2 -y
    
        # allow ruby.exe outgoing traffic
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")   
        $rubyExeFilePath = (Get-Command ruby.exe).Path
        Import-Module NetSecurity
        New-NetFirewallRule -DisplayName "Ruby" -Direction Outbound -Program $rubyExeFilePath -Protocol TCP -Action Allow
    
        # workaround cert issue
        $certUrl = "https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/AddTrustExternalCARoot-2048.pem"
        $pemTargetFilePath = (gem which rubygems) -replace ".rb"
        $pemTargetFilePath = [io.path]::combine($pemTargetFilePath, "ssl_certs", (Split-Path $certUrl -leaf))
        ( new-object net.webclient ).DownloadFile($certUrl,$pemTargetFilePath)   
        Unblock-File -Path $pemTargetFilePath
    }
    
    if ( Get-UAC )
    {
        Disable-UAC
        Invoke-Reboot
    }
    
    Test


**I'm running this using:**

    Set-ExecutionPolicy Unrestricted -Force
    iex ( ( new-object net.webclient ).DownloadString( 'https://chocolatey.org/install.ps1' ) )
    cinst Boxstarter -y
    BoxstarterShell.bat
    $creds = Get-Credential
    Install-BoxstarterPackage -PackageName PATH_TO_FILE_HERE -Credential $creds

**Comment by mwrock** [comment]
I see the issue. Its technically a bug in chocolatey but  I can correct it on boxstarter's side since it makes no sense to send a fix to the old chocolatey. I have a fix pending and should release in the next few days.

**Comment by mwrock** [comment]
this fix is now released.

**Comment by SurajGupta** [comment]
thanks for the quick turnaround on this!
