### ISSUE TITLE
How to restart shell to pick up PATH updates?

### ISSUE THREAD

**Issue by vorou** [mwrock/boxstarter#84]
I'd like to invoke git in a boxstarter script. The problem is I just installed it w/ `cinst git` and its `chocolateyInstall.ps1` doesn't update current shell `PATH`. So, I have to restart the shell to pick up the changes.

Is `Invoke-Reboot` the only way?

**Comment by mwrock** [comment]
You can always call git using its full path which will be located at `C:\Program Files (x86)\Git\bin\git.exe` on most 64 bit systems.

**Comment by vorou** [comment]
Indeed, thanks!
