### ISSUE TITLE
Cannot find drive exception after reboot

### ISSUE THREAD

**Issue by bradlunde** [mwrock/boxstarter#87]
When using boxstarter to install chocolatey packages which mounts an ISO an exception is thrown during the reboot process that boxstarter is unable to handle.  Not sure if there is a work around possible as there are already try/catch statements around the script.

The drive letter below is mounted and then unmounted during the installation of a chocolatey package.

I can send script files as well as a log file if it would be helpful.

Exception from log is as follows:
[2015-05-07T11:12:23.6973930-07:00:::PID 2576] Boxstarter: Exit Code: 0
[2015-05-07T11:12:23.6973930-07:00:::PID 2576] Boxstarter: There was an error calling chocolatey
[2015-05-07T11:12:23.9630124-07:00:::PID 2576] Error from chocolatey: 

ErrorRecord                 : Cannot find drive. A drive with the name 'W' does
                               not exist.
ItemName                    : W
SessionStateCategory        : Drive
StackTrace                  :    at System.Management.Automation.SessionStateIn
                              ternal.GetDrive(String name, Boolean automount)
                                 at System.Management.Automation.SessionStateIn
                              ternal.GetDrive(String name, Boolean automount)
                                 at System.Management.Automation.LocationGlobbe
                              r.GetDriveRootRelativePathFromPSPath(String path,
                               CmdletProviderContext context, Boolean escapeCur
                              rentLocation, PSDriveInfo& workingDriveForPath, C
                              mdletProvider& providerInstance)
                                 at System.Management.Automation.LocationGlobbe
                              r.GetProviderPath(String path, CmdletProviderCont
                              ext context, ProviderInfo& provider, PSDriveInfo&
                               drive)
                                 at System.Management.Automation.LocationGlobbe
                              r.GetGlobbedProviderPathsFromMonadPath(String pat
                              h, Boolean allowNonexistingPaths, CmdletProviderC
                              ontext context, ProviderInfo& provider, CmdletPro
                              vider& providerInstance)
                                 at System.Management.Automation.LocationGlobbe
                              r.GetGlobbedProviderPathsFromMonadPath(String pat
                              h, Boolean allowNonexistingPaths, ProviderInfo& p
                              rovider, CmdletProvider& providerInstance)
                                 at System.Management.Automation.PathUtils.Reso
                              lveFilePath(String filePath, PSCmdlet command, Bo
                              olean isLiteralPath)
                                 at System.Management.Automation.PathUtils.Mast
                              erStreamOpen(PSCmdlet cmdlet, String filePath, En
                              coding resolvedEncoding, Boolean defaultEncoding,
                               Boolean Append, Boolean Force, Boolean NoClobber
                              , FileStream& fileStream, StreamWriter& streamWri
                              ter, FileInfo& readOnlyFileInfo, Boolean isLitera
                              lPath)
                                 at Microsoft.PowerShell.Commands.OutFileComman
                              d.InstantiateLineOutputInterface()
                                 at Microsoft.PowerShell.Commands.OutFileComman
                              d.BeginProcessing()
                                 at System.Management.Automation.Cmdlet.DoBegin
                              Processing()
                                 at System.Management.Automation.CommandProcess
                              orBase.DoBegin()
WasThrownFromThrowStatement : False
Message                     : Cannot find drive. A drive with the name 'W' does
                               not exist.
Data                        : {}
InnerException              : 
TargetSite                  : System.Management.Automation.PSDriveInfo GetDrive
                              (System.String, Boolean)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

**Comment by mwrock** [comment]
looks like this error is coming from somewhere in the chocolatey script. One thing you might try is to explicitly unmount the iso when you are done with it.

**Comment by bradlunde** [comment]
The script does does dismount the drive after the install and before the reboot, tried with both imdisk and the iso mount powershell commands.  OS is Server 2014.

I would agree that the source is in chocolatey but when i run the chocolatey commands outside of the boxstarter environment I don't see any issues.  Also the exception is thrown before the temp package is run again as the try/catch inside the chocolateyinstall.ps1 script does not catch this exception.

Currently the two applications I need to install I do last as the script will not be run again after the reboot.  There are a few more things I would like it to do after the applications are installed but just getting it to the current state is a big win.

**Comment by mwrock** [comment]
It would be helpful to see the script. Its hard to tell from the stacktrace but it seems like something may be trying to write a file on that drive based on `OutFileCommand` in the stack trace. Is the snippet from the log above the very end of the log or was there more info emitted afterwards? If its not the end it would be helpful to see the very next entry.

You said this is on OS 2014. Did you mean 2012? Also is this a local or remote install?

**Comment by mwrock** [comment]
Closing for now but can reopen if more info is available.
