### ISSUE TITLE
Needing to rerun Boxstarter multiple times and still doesn't complete

### ISSUE THREAD

**Issue by mwrock** [mwrock/boxstarter#9]
Migrated from https://boxstarter.codeplex.com/workitem/71

OS: win 7 x64 Evaluation version running in Vmware Fusion VM 

Since WebLauncher didn't work I manually installed Chocolatey and then Boxstarter and then from Boxstarter shell ran this: 

PS C:> Install-BoxstarterPackage -PackageName https://gist.githubusercontent.co 
m/clarity99/123650a8387d3fc8bd79/raw/gistfile1.txt 

This started working but with various issues. SP1 dialog was left on the screen. 
I had to restart process a few times to continue with the installation and finally it came to this: 

PS C:> Install-BoxstarterPackage -PackageName https://gist.githubusercontent.co 
m/clarity99/123650a8387d3fc8bd79/raw/gistfile1.txt 
Boxstarter: Installing package https://gist.githubusercontent.com/clarity99/1236 
50a8387d3fc8bd79/raw/gistfile1.txt 
Boxstarter Version 2.4.15 
(c) 2014 Matt Wrock. http://boxstarter.org 

Boxstarter: Disabling Automatic Updates from Windows Update 
Calling 'C:\Chocolatey\chocolateyinstall\nuget.exe pack temp_BoxstarterPackage\t 
emp_BoxstarterPackage.nuspec -NoPackageAnalysis'. 
Attempting to build package from 'temp_BoxstarterPackage.nuspec'. 
Successfully created package 'C:\Users\rob\AppData\Roaming\Boxstarter\BuildPacka 
ges\temp_BoxstarterPackage.1.0.0.nupkg'. 

Boxstarter: Created a temporary package temp_BoxstarterPackage from https://gist .githubusercontent.com/clarity99/123650a8387d3fc8bd79/raw/gistfile1.txt in C:\Us 
ers\rob\AppData\Roaming\Boxstarter\BuildPackages
Boxstarter starting Calling Chocolatey to install temp_BoxstarterPackage. This 
may take several minutes to complete... 
Chocolatey (v0.9.8.23) is installing 'temp_BoxstarterPackage' and dependencies. 
By installing you accept the license for 'temp_BoxstarterPackage' and each depen 
dency you are installing. 
'temp_BoxstarterPackage 1.0.0' already installed. 
If you want to reinstall the current version of an existing package, please use 
the -force command.
Finished installing 'temp_BoxstarterPackage' and dependencies - if errors not sh 
own in console, none detected. Check log for errors if unsure.
Boxstarter finished Calling Chocolatey to install temp_BoxstarterPackage. This 
may take several minutes to complete... 00:00:02.1211673 
Boxstarter: Enabling Automatic Updates from Windows Update
Completed : True 
Errors : {} 
ComputerName : localhost 
StartTime : 05/04/2014 19:22:45 
FinishTime : 05/04/2014 19:22:50 

However, it only installed up to an including NugetPackageExplorer. 

Now, it won't continue.

**Comment by jnus** [comment]
Got the same behavior on a couple of hosts, where it thinks the package is already installed:
> 'temp_BoxstarterPackage 1.0.0' already installed.
Any idea why?

Thanks 
/Jasper

**Comment by mwrock** [comment]
Not sure. When using a gist, boxstarter generates the `temp_BoxstarterPackage`. Boxstarter will always remove the package from the chocolatey cache before installing to avoid this situation. One possibility that comes to mind is that the host is somehow in a weird transitory state between chocolatey versions where chocolatey moved its cache from `c:\chocolatey` to `c:\ProgramData\Chocolatey` and boxstarter is removing from one location and chocolatey is looking in another. You might try looking to see if you have two chocolatey installations and also checking if the `ChocolateyInstall` environment variable is pointing to the correct location.

**Comment by mwrock** [comment]
just going over open issues and saw this. This was fixed. see #60
