### ISSUE TITLE
Make Boxstarter install the latest Chocolatey version

### ISSUE THREAD

**Issue by C-Duv** [mwrock/boxstarter#90]
Boxstarter seems to install Chocolatey v0.9.8.33 whereas v0.9.9 is available.

Is it possible for Boxstarter to install latest Chocolatey version?
I tried running `chocolatey update` inside my installation script without success (maybe a new command shell should be used to use updated chocolatey?).
Should it work via script as I tried or should I manually change *boxstarter/boxstarter.config* file?

**Comment by gep13** [comment]
I believe that this could be a duplicate of this issue: https://github.com/mwrock/boxstarter/issues/89

**Comment by mwrock** [comment]
yep. this is a duplicate please see the comments on that issue for more info.

**Comment by C-Duv** [comment]
Thanks for the answer : I'll adapt my Boxstarter scripts so that they use the 0.9.8's syntax for now then.
