### ISSUE TITLE
Get-Item : Cannot find path 'C:\Users\Administrator\AppData\Local\Apps\2.0\..... because it does not exist.

### ISSUE THREAD

**Issue by neoKushan** [mwrock/boxstarter#98]
Trying to run Boxstarter on a brand new server 2012 R2 install. I'm using the web launch, the clickonce installer downloads and runs just fine and Chocolatey _seems_ to install ok, but when Boxstarter comes to run it, it keels over. It's the same when trying to run the VM setup command. Below is a full dump of the command line:

		Boxstarter: Boxstarter will use its own private version of Chocolatey...

		7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

		Processing archive: C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstal
		l\chocolatey.zip

		Extracting  _rels\.rels
		Extracting  chocolatey.nuspec
		Extracting  tools\chocolateyInstall.ps1
		Extracting  tools\chocolateysetup.psm1
		Extracting  tools\init.ps1
		Extracting  tools\chocolateyInstall\chocolatey.cmd
		Extracting  tools\chocolateyInstall\chocolatey.config
		Extracting  tools\chocolateyInstall\chocolatey.ps1
		Extracting  tools\chocolateyInstall\LICENSE.txt
		Extracting  tools\chocolateyInstall\NuGet.exe
		Extracting  tools\chocolateyInstall\NuGet.exe.ignore
		Extracting  tools\chocolateyInstall\functions\Append-Log.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Cygwin.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Help.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Install.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallAll.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallExtension.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallIfMissing.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-List.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-NuGet.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Pack.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-PackagesConfig.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Push.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Python.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-RubyGem.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Sources.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Uninstall.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Update.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-Version.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-WebPI.ps1
		Extracting  tools\chocolateyInstall\functions\Chocolatey-WindowsFeatures.ps1
		Extracting  tools\chocolateyInstall\functions\Create-InstallLogIfNotExists.ps1
		Extracting  tools\chocolateyInstall\functions\Delete-ExistingErrorLog.ps1
		Extracting  tools\chocolateyInstall\functions\Generate-BinFile.ps1
		Extracting  tools\chocolateyInstall\functions\Get-ChocolateyBins.ps1
		Extracting  tools\chocolateyInstall\functions\Get-ConfigValue.ps1
		Extracting  tools\chocolateyInstall\functions\Get-GlobalConfigValue.ps1
		Extracting  tools\chocolateyInstall\functions\Get-LatestPackageVersion.ps1
		Extracting  tools\chocolateyInstall\functions\Get-LongPackageVersion.ps1
		Extracting  tools\chocolateyInstall\functions\Get-PackageFoldersForPackage.ps1
		Extracting  tools\chocolateyInstall\functions\Get-PackageFolderVersions.ps1
		Extracting  tools\chocolateyInstall\functions\Get-SourceArguments.ps1
		Extracting  tools\chocolateyInstall\functions\Get-Sources.ps1
		Extracting  tools\chocolateyInstall\functions\Get-UserConfigValue.ps1
		Extracting  tools\chocolateyInstall\functions\Get-VersionsForComparison.ps1
		Extracting  tools\chocolateyInstall\functions\Move-BadInstall.ps1
		Extracting  tools\chocolateyInstall\functions\Remove-BinFile.ps1
		Extracting  tools\chocolateyInstall\functions\Remove-LastInstallLog.ps1
		Extracting  tools\chocolateyInstall\functions\Run-ChocolateyProcess.ps1
		Extracting  tools\chocolateyInstall\functions\Run-ChocolateyPS1.ps1
		Extracting  tools\chocolateyInstall\functions\Run-NuGet.ps1
		Extracting  tools\chocolateyInstall\functions\Write-UserConfig.ps1
		Extracting  tools\chocolateyInstall\helpers\chocolateyInstaller.psm1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-BinRoot.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-CheckSumValid.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-ChocolateyUnzip.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-ChocolateyWebFile.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariable.ps
		1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariableNam
		es.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-FtpFile.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-ProcessorBits.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-UACEnabled.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-VirusCheckValid.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-WebFile.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Get-WebHeaders.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyDesktopL
		ink.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyEnvironm
		entVariable.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyExplorer
		MenuItem.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyFileAsso
		ciation.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyInstallP
		ackage.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPackage.
		ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPath.ps1

		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPinnedTa
		skBarItem.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPowershe
		llCommand.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyVsixPack
		age.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyZipPacka
		ge.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Set-EnvironmentVariable.ps
		1
		Extracting  tools\chocolateyInstall\helpers\functions\Start-ChocolateyProcessAsA
		dmin.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Test-ProcessAdminRights.ps
		1
		Extracting  tools\chocolateyInstall\helpers\functions\Uninstall-ChocolateyPackag
		e.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\UnInstall-ChocolateyZipPac
		kage.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Update-SessionEnvironment.
		ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-ChocolateyFailure.ps
		1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-ChocolateySuccess.ps
		1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-Debug.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-Error.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-FileUpdateLog.ps1
		Extracting  tools\chocolateyInstall\helpers\functions\Write-Host.ps1
		Extracting  tools\chocolateyInstall\redirects\choco.exe
		Extracting  tools\chocolateyInstall\redirects\choco.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\chocolatey.exe
		Extracting  tools\chocolateyInstall\redirects\chocolatey.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cinst.exe
		Extracting  tools\chocolateyInstall\redirects\cinst.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\clist.exe
		Extracting  tools\chocolateyInstall\redirects\clist.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cpack.exe
		Extracting  tools\chocolateyInstall\redirects\cpack.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cpush.exe
		Extracting  tools\chocolateyInstall\redirects\cpush.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cuninst.exe
		Extracting  tools\chocolateyInstall\redirects\cuninst.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cup.exe
		Extracting  tools\chocolateyInstall\redirects\cup.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\cver.exe
		Extracting  tools\chocolateyInstall\redirects\cver.exe.ignore
		Extracting  tools\chocolateyInstall\redirects\RefreshEnv.cmd
		Extracting  tools\chocolateyInstall\tools\7za.exe
		Extracting  tools\chocolateyInstall\tools\7za.exe.ignore
		Extracting  tools\chocolateyInstall\tools\7za.exe.manifest
		Extracting  tools\chocolateyInstall\tools\7zip.license.txt
		Extracting  tools\chocolateyInstall\tools\checksum.exe
		Extracting  tools\chocolateyInstall\tools\checksum.exe.ignore
		Extracting  tools\chocolateyInstall\tools\checksum.license.txt
		Extracting  tools\chocolateyInstall\tools\shimgen.exe
		Extracting  tools\chocolateyInstall\tools\shimgen.exe.ignore
		Extracting  tools\chocolateyInstall\tools\shimgen.license.txt
		Extracting  package\services\metadata\core-properties\e1f5c738a3c0485aa4d3dddb61
		8d90c1.psmdcp
		Extracting  [Content_Types].xml

		Everything is Ok

		Files: 119
		Size:       2741264
		Compressed: 1017239
		Creating ChocolateyInstall as an Environment variable (targeting 'Machine') and
		setting it to 'C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH
		3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey'
		We are setting up the Chocolatey repository for NuGet packages that should be at
		 the machine level. Think executables/application packages, not library packages
		.
		That is what Chocolatey NuGet goodness is for. The repository is set up at 'C:\U
		sers\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b
		971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey'.
		The packages themselves go to 'C:\Users\Administrator\AppData\Local\Apps\2.0\97A
		Q8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Ch
		ocolatey\lib' (i.e. C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4
		VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey\li
		b\yourPackageName).
		A shim file for the command line goes to 'C:\Users\Administrator\AppData\Local\A
		pps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf4
		7f549e6d\Chocolatey\bin' and points to an executable in 'C:\Users\Administrator\
		AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_000
		2.0005_2b3bdbf47f549e6d\Chocolatey\lib\yourPackageName'.

		Creating Chocolatey NuGet folders if they do not already exist.

		Copying the contents of 'C:\Users\Administrator\AppData\Local\Temp\2\chocolatey\
		chocInstall\tools\chocolateyInstall' to 'C:\Users\Administrator\AppData\Local\Ap
		ps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47
		f549e6d\Chocolatey'.
		PATH environment variable does not have C:\Users\Administrator\AppData\Local\App
		s\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f
		549e6d\Chocolatey\bin in it. Adding...
		Chocolatey is now ready.
		You can call chocolatey from anywhere, command line or powershell by typing choc
		o.
		Run choco /? for a list of functions.
		You may need to shut down and restart powershell and/or consoles first prior to
		using chocolatey.
		Boxstarter: Installing package https://gist.github.com/neoKushan/7590e6bbe4af75b
		ccb37/raw
		Boxstarter Version 2.5.3
		(c) 2015 Matt Wrock. http://boxstarter.org

		Boxstarter: Disabling Automatic Updates from Windows Update
		Calling 'C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B
		\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey\chocolateyins
		tall\nuget.exe pack temp_BoxstarterPackage\temp_BoxstarterPackage.nuspec -NoPack
		ageAnalysis -NonInteractive'.
		Attempting to build package from 'temp_BoxstarterPackage.nuspec'.
		Successfully created package 'C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ
		8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Bui
		ldPackages\temp_BoxstarterPackage.1.0.0.nupkg'.
		Your package has been built. Using Boxstarter.bat  or Install-BoxstarterPackage
		 will run this package.
		Boxstarter: Created a temporary package temp_BoxstarterPackage from https://gist
		.github.com/neoKushan/7590e6bbe4af75bccb37/raw in C:\Users\Administrator\AppData
		\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_
		2b3bdbf47f549e6d\BuildPackages
		+ Boxstarter starting Calling Boxstarter's vendored Chocolatey to install temp_B
		oxstarterPackage. This may take several minutes to complete...
		Chocolatey (v0.9.8.33) is installing 'temp_BoxstarterPackage' and dependencies.
		By installing you accept the license for 'temp_BoxstarterPackage' and each depen
		dency you are installing.

		temp_BoxstarterPackage v1.0.0
		Get-Item : Cannot find path 'C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ
		8MGC.4PH\4VH4HH3K.18B\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Bo
		xstarter.HyperV\Boxstarter.HyperV.psd1' because it does not exist.
		At C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs
		..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Boxstarter.Chocolatey\Resolv
		e-VMPlugin.ps1:10 char:24
		+         $unNormalized=(Get-Item "$PSScriptRoot\..\Boxstarter.$provider\Boxsta
		rte ...
		+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		~~~
			+ CategoryInfo          : ObjectNotFound: (C:\Users\Admini...ter.HyperV.ps
		   d1:String) [Get-Item], ItemNotFoundException
			+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetIt
		   emCommand

		Write-Error : Package 'temp_BoxstarterPackage v1.0.0' did not install successfu
		lly: Cannot retrieve the dynamic parameters for the cmdlet. Cannot bind argumen
		t to parameter 'Name' because it is null.
		At C:\Users\Administrator\AppData\Local\Apps\2.0\97AQ8MGC.4PH\4VH4HH3K.18B\boxs
		..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey\chocolateyinstall
		\functions\Chocolatey-NuGet.ps1:90 char:17
		+                 Write-Error "Package `'$installedPackageName v$installedPacka
		geV ...
		+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
		   tion
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
		   n,Write-Error

		Finished installing 'temp_BoxstarterPackage' and dependencies - if errors not sh
		own in console, none detected. Check log for errors if unsure.
		Write-Error : Chocolatey reported an unsuccessful exit code of 1
		At line:124 char:21
		+                     Write-Error "Chocolatey reported an unsuccessful exit cod
		e o ...
		+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
		   tion
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
		   n,Write-Error

		+ Boxstarter finished Calling Boxstarter's vendored Chocolatey to install temp_B
		oxstarterPackage. This may take several minutes to complete... 00:00:05.1499427
		True
		Boxstarter: Enabling Automatic Updates from Windows Update
		Type ENTER to exit:

For reference, the command I ran is this:
START http://boxstarter.org/package/nr/url?https://gist.github.com/neoKushan/7590e6bbe4af75bccb37/raw

I have disabled UAC manually and this was run from an elevated command prompt. Any idea?

**Comment by mwrock** [comment]
The problem here is the use of `Enable-BoxstarterVM`.  It was not intended to be used in the way you are invoking it. That command works with the `Boxstarter.Hyperv` or `Boxstarter.Azure` module to enable an existing VM to be accessed by boxstarter remotely. When using the web installer, niether of those modules are installed because using the web installer implies you are running the package locally.

However, Boxstarter should definitely be raising a more comprehensible and actionable error message.

**Comment by neoKushan** [comment]
Thanks for the response! Sorry if I have missed it on the documentation, but is there a way to tell which commands are supported via this method?

I was getting a similar error before I added the Enable-BoxstarterVM command, figuring that perhaps it was necessary due to this being a VM but I believe it's the Enable-RemoteDesktop command that was originally causing me issues. After removing both commands, the script runs perfectly.

**Comment by mwrock** [comment]
Mind showing the error you get with just `Enable-RemoteDesktop`? Thanks!

**Comment by neoKushan** [comment]
Sure thing! Temprarily edited that script to include it. Seems to be this:

    Exception calling "SetAllowTSConnections" : "Invalid operation "

Here's the full log:

		Boxstarter: Installing package https://gist.github.com/neoKushan/7590e6bbe4af75b
		ccb37/raw
		Boxstarter Version 2.5.3
		(c) 2015 Matt Wrock. http://boxstarter.org

		Boxstarter: Disabling Automatic Updates from Windows Update
		Calling 'C:\Users\Administrator.ICCSOL\AppData\Local\Apps\2.0\WY6O2WJ7.LQ2\T0NEA
		EB7.CMW\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey\chocol
		ateyinstall\nuget.exe pack temp_BoxstarterPackage\temp_BoxstarterPackage.nuspec
		-NoPackageAnalysis -NonInteractive'.
		Attempting to build package from 'temp_BoxstarterPackage.nuspec'.
		Successfully created package 'C:\Users\Administrator.ICCSOL\AppData\Local\Apps\2
		.0\WY6O2WJ7.LQ2\T0NEAEB7.CMW\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549
		e6d\BuildPackages\temp_BoxstarterPackage.1.0.0.nupkg'.
		Your package has been built. Using Boxstarter.bat  or Install-BoxstarterPackage
		 will run this package.
		Boxstarter: Created a temporary package temp_BoxstarterPackage from https://gist
		.github.com/neoKushan/7590e6bbe4af75bccb37/raw in C:\Users\Administrator.ICCSOL\
		AppData\Local\Apps\2.0\WY6O2WJ7.LQ2\T0NEAEB7.CMW\boxs..tion_b971437cd3e1b01e_000
		2.0005_2b3bdbf47f549e6d\BuildPackages
		+ Boxstarter starting Calling Boxstarter's vendored Chocolatey to install temp_B
		oxstarterPackage. This may take several minutes to complete...
		Chocolatey (v0.9.8.33) is installing 'temp_BoxstarterPackage' and dependencies.
		By installing you accept the license for 'temp_BoxstarterPackage' and each depen
		dency you are installing.

		temp_BoxstarterPackage v1.0.0
		Boxstarter: Disabling UAC
		Boxstarter: Setting Windows Explorer options...
		Boxstarter: Restarting the Windows Explorer process...
		Boxstarter: Restarting the Windows Explorer process...
		Boxstarter: Enabling Remote Desktop...
		Write-Error : Package 'temp_BoxstarterPackage v1.0.0' did not install successfu
		lly: Exception calling "SetAllowTSConnections" : "Invalid operation "
		At C:\Users\Administrator.ICCSOL\AppData\Local\Apps\2.0\WY6O2WJ7.LQ2\T0NEAEB7.C
		MW\boxs..tion_b971437cd3e1b01e_0002.0005_2b3bdbf47f549e6d\Chocolatey\chocolatey
		install\functions\Chocolatey-NuGet.ps1:90 char:17
		+                 Write-Error "Package `'$installedPackageName v$installedPacka
		geV ...
		+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
		   tion
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
		   n,Write-Error

		Finished installing 'temp_BoxstarterPackage' and dependencies - if errors not sh
		own in console, none detected. Check log for errors if unsure.
		Write-Error : Chocolatey reported an unsuccessful exit code of 1
		At line:124 char:21
		+                     Write-Error "Chocolatey reported an unsuccessful exit cod
		e o ...
		+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
		   tion
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
		   n,Write-Error

		+ Boxstarter finished Calling Boxstarter's vendored Chocolatey to install temp_B
		oxstarterPackage. This may take several minutes to complete... 00:00:09.1837276
		True
		Boxstarter: Enabling Automatic Updates from Windows Update
		Type ENTER to exit:

**Comment by mwrock** [comment]
Interesting. Seems like I have run into this before where something to do with the box prevented remote desktop from being enabled. This works on my clean 2012R2 Hyper-V VM. Could you run this on the VM?:
```
$obj = Get-WmiObject -Class "Win32_TerminalServiceSetting" -Namespace root\cimv2\terminalservices
$obj.SetAllowTsConnections(1,1)
```
This is essentially what `Enable-RemoteDesktop` calls. Perhaps running it by itself will produce a better error message or some HRESULT code pointing to some clue.

**Comment by neoKushan** [comment]
Aha, I suspect I know what the issue is (once again, me being stupid). First, the output of the command:

	PS C:\Users\Administrator.ICCSOL> $obj = Get-WmiObject -Class "Win32_TerminalServiceSetting" -Namespace root\cimv2\termi
	nalservices `
	>> $obj.SetAllowTsConnections(1,1)
	>>
	Exception calling "SetAllowTSConnections" : "Invalid operation "
	At line:1 char:1
	+ $obj = Get-WmiObject -Class "Win32_TerminalServiceSetting" -Namespace root\cimv2 ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
		+ FullyQualifiedErrorId : WMIMethodException

	PS C:\Users\Administrator.ICCSOL>

Now I think the problem is that this machine is domain joined AND there's a group policy to enable RDP anyway. I can't even change this option myself: http://i.imgur.com/EDAqMj0.png

**Comment by mwrock** [comment]
Ah yeah thats it. I really wish there was an easier way to discover that or the command would report a more actionable error message.
